package com.pma.mpsr;

import java.text.ParseException;

import com.pma.vaadin.converter.DateToSqlTimestampConverter;
import com.pma.vaadin.converter.NumberToBigDecimalConverter;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;

@SuppressWarnings("serial")
public class Form_3_0_0 extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TextField targetBudget;
	@AutoGenerated
	private Label label_targetBudget;
	@AutoGenerated
	private TextField req2Auth;
	@AutoGenerated
	private Label req2Total;
	@AutoGenerated
	private TextField req2Post;
	@AutoGenerated
	private TextField req2Year4;
	@AutoGenerated
	private TextField req2Year3;
	@AutoGenerated
	private TextField req2Year2;
	@AutoGenerated
	private TextField req2Year1;
	@AutoGenerated
	private TextField req2Current;
	@AutoGenerated
	private TextField req2Prior;
	@AutoGenerated
	private PopupDateField dateReq2;
	@AutoGenerated
	private TextField req1Auth;
	@AutoGenerated
	private Label req1Total;
	@AutoGenerated
	private TextField req1Post;
	@AutoGenerated
	private TextField req1Year4;
	@AutoGenerated
	private TextField req1Year3;
	@AutoGenerated
	private TextField req1Year2;
	@AutoGenerated
	private TextField req1Year1;
	@AutoGenerated
	private TextField req1Current;
	@AutoGenerated
	private TextField req1Prior;
	@AutoGenerated
	private PopupDateField dateReq1;
	@AutoGenerated
	private TextField req0Auth;
	@AutoGenerated
	private Label req0Total;
	@AutoGenerated
	private TextField req0Post;
	@AutoGenerated
	private TextField req0Year4;
	@AutoGenerated
	private TextField req0Year3;
	@AutoGenerated
	private TextField req0Year2;
	@AutoGenerated
	private TextField req0Year1;
	@AutoGenerated
	private TextField req0Current;
	@AutoGenerated
	private TextField req0Prior;
	@AutoGenerated
	private PopupDateField dateReq0;
	@AutoGenerated
	private Label totalTotal;
	@AutoGenerated
	private Label totalPost;
	@AutoGenerated
	private Label totalYear4;
	@AutoGenerated
	private Label totalYear3;
	@AutoGenerated
	private Label totalYear2;
	@AutoGenerated
	private Label totalYear1;
	@AutoGenerated
	private Label totalCurrent;
	@AutoGenerated
	private Label totalPrior;
	@AutoGenerated
	private PopupDateField dateTotal;
	@AutoGenerated
	private Label rncTotal;
	@AutoGenerated
	private TextField rncPost;
	@AutoGenerated
	private TextField rncYear4;
	@AutoGenerated
	private TextField rncYear3;
	@AutoGenerated
	private TextField rncYear2;
	@AutoGenerated
	private TextField rncYear1;
	@AutoGenerated
	private TextField rncCurrent;
	@AutoGenerated
	private TextField rncPrior;
	@AutoGenerated
	private Label baseTotal;
	@AutoGenerated
	private TextField basePost;
	@AutoGenerated
	private TextField baseYear4;
	@AutoGenerated
	private TextField baseYear3;
	@AutoGenerated
	private TextField baseYear2;
	@AutoGenerated
	private TextField baseYear1;
	@AutoGenerated
	private TextField baseCurrent;
	@AutoGenerated
	private TextField basePrior;
	@AutoGenerated
	private Label label_Auth;
	@AutoGenerated
	private Label label_Total;
	@AutoGenerated
	private TextField yearPost;
	@AutoGenerated
	private TextField year4;
	@AutoGenerated
	private TextField year3;
	@AutoGenerated
	private TextField year2;
	@AutoGenerated
	private TextField year1;
	@AutoGenerated
	private TextField yearCurrent;
	@AutoGenerated
	private Label label_Prior;
	@AutoGenerated
	private Label label_Request2;
	@AutoGenerated
	private Label label_Request1;
	@AutoGenerated
	private Label label_Request0;
	@AutoGenerated
	private Label label_TotalProject;
	@AutoGenerated
	private Label label_RnC;
	@AutoGenerated
	private Label label_base;
	@AutoGenerated
	private Label label_Millions;
	@AutoGenerated
	private TextArea desc1;
	@AutoGenerated
	private Label labelPrototype;
	FieldGroup fieldGroup = new FieldGroup();

	DateToSqlTimestampConverter dateConverter = new DateToSqlTimestampConverter();
	NumberToBigDecimalConverter numberConverter = new NumberToBigDecimalConverter();

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public Form_3_0_0() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		initFields();
		initListeners();
	}

	private void initFields() {

		mainLayout.addStyleName("form-3");
		Label[] labels = { label_Millions, label_base, label_RnC, label_TotalProject, label_Request0, label_Request1, label_Request2 };
		for (Label label : labels) {
			label.addStyleName("request");
		}

		labelPrototype.setValue("Prototype");

		desc1.setCaption(MPSRUI.TREE_3);
		desc1.setNullRepresentation("");
		fieldGroup.bind(desc1, "DESC1");

		TextField[] headerFields = { yearCurrent, year1, year2, year3, year4, yearPost };
		String[] headerPropertyIds = { "HEADER_YR0", "HEADER_YR1", "HEADER_YR2", "HEADER_YR3", "HEADER_YR4", "HEADER_POST_YEAR" };
		for (int i = 0; i < headerFields.length; i++) {
			headerFields[i].setNullRepresentation("");
			fieldGroup.bind(headerFields[i], headerPropertyIds[i]);
		}

		TextField[] numberFields = { basePrior, baseCurrent, baseYear1, baseYear2, baseYear3, baseYear4, basePost, rncPrior, rncCurrent, rncYear1, rncYear2,
				rncYear3, rncYear4, rncPost, req0Prior, req0Current, req0Year1, req0Year2, req0Year3, req0Year4, req0Post, req0Auth, req1Prior, req1Current,
				req1Year1, req1Year2, req1Year3, req1Year4, req1Post, req1Auth, req2Prior, req2Current, req2Year1, req2Year2, req2Year3, req2Year4, req2Post,
				req2Auth };
		String[] numberPropertyIds = { "BASE_PRIOR_YEAR", "BASE_YR0", "BASE_YR1", "BASE_YR2", "BASE_YR3", "BASE_YR4", "BASE_POST_YEAR", "RC_PRIOR_YEAR",
				"RC_YR0", "RC_YR1", "RC_YR2", "RC_YR3", "RC_YR4", "RC_POST_YEAR", "REQ0_PRIOR_YEAR", "REQ0_YR0", "REQ0_YR1", "REQ0_YR2", "REQ0_YR3",
				"REQ0_YR4", "REQ0_POST_YEAR", "REQ0_AUTH", "REQ1_PRIOR_YEAR", "REQ1_YR0", "REQ1_YR1", "REQ1_YR2", "REQ1_YR3", "REQ1_YR4", "REQ1_POST_YEAR",
				"REQ1_AUTH", "REQ2_PRIOR_YEAR", "REQ2_YR0", "REQ2_YR1", "REQ2_YR2", "REQ2_YR3", "REQ2_YR4", "REQ2_POST_YEAR", "REQ2_AUTH" };
		for (int i = 0; i < numberFields.length; i++) {
			numberFields[i].setNullRepresentation("-");
			numberFields[i].setConverter(numberConverter);
			fieldGroup.bind(numberFields[i], numberPropertyIds[i]);
		}

		PopupDateField[] dateFields = { dateTotal, dateReq0, dateReq1, dateReq2 };
		String[] datePropertyIds = { "TOTAL_DATE", "REQ0_DATE", "REQ1_DATE", "REQ2_DATE" };
		for (int i = 0; i < dateFields.length; i++) {
			dateFields[i].setConverter(dateConverter);
			fieldGroup.bind(dateFields[i], datePropertyIds[i]);
		}

		targetBudget.setNullRepresentation("");
		targetBudget.addStyleName("targetbudget");
		fieldGroup.bind(targetBudget, "TARGETBUDGET");

		fieldGroup.setBuffered(false);
	}

	@Override
	public void setReadOnly(boolean readOnly) {
		TextField[] headerFields = { yearCurrent, year1, year2, year3, year4, yearPost };
		for (int i = 0; i < headerFields.length; i++) {
			headerFields[i].setReadOnly(readOnly);
		}

		TextField[] numberFields = { basePrior, baseCurrent, baseYear1, baseYear2, baseYear3, baseYear4, basePost, rncPrior, rncCurrent, rncYear1, rncYear2,
				rncYear3, rncYear4, rncPost, req0Prior, req0Current, req0Year1, req0Year2, req0Year3, req0Year4, req0Post, req0Auth, req1Prior, req1Current,
				req1Year1, req1Year2, req1Year3, req1Year4, req1Post, req1Auth, req2Prior, req2Current, req2Year1, req2Year2, req2Year3, req2Year4, req2Post,
				req2Auth };
		for (int i = 0; i < numberFields.length; i++) {
			numberFields[i].setReadOnly(readOnly);
		}

		PopupDateField[] dateFields = { dateTotal, dateReq0, dateReq1, dateReq2 };
		for (int i = 0; i < dateFields.length; i++) {
			dateFields[i].setReadOnly(readOnly);
		}

		targetBudget.setReadOnly(readOnly);

	}

	private void initListeners() {

		final TextField[] baseFields = { basePrior, baseCurrent, baseYear1, baseYear2, baseYear3, baseYear4, basePost };
		final TextField[] rncFields = { rncPrior, rncCurrent, rncYear1, rncYear2, rncYear3, rncYear4, rncPost };
		final Label[] totalLables = { baseTotal, rncTotal };
		final TextField[] req0Fields = { req0Prior, req0Current, req0Year1, req0Year2, req0Year3, req0Year4, req0Post };
		final TextField[] req1Fields = { req1Prior, req1Current, req1Year1, req1Year2, req1Year3, req1Year4, req1Post };
		final TextField[] req2Fields = { req2Prior, req2Current, req2Year1, req2Year2, req2Year3, req2Year4, req2Post };

		basePrior.addValueChangeListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				setRequestTotal(baseFields, baseTotal);
				setYearSum(new TextField[] { basePrior, rncPrior }, totalPrior);
				setSum(totalLables, totalTotal);
			}
		});

		baseCurrent.addValueChangeListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				setRequestTotal(baseFields, baseTotal);
				setYearSum(new TextField[] { baseCurrent, rncCurrent }, totalCurrent);
				setSum(totalLables, totalTotal);
			}
		});

		baseYear1.addValueChangeListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				setRequestTotal(baseFields, baseTotal);
				setYearSum(new TextField[] { baseYear1, rncYear1 }, totalYear1);
				setSum(totalLables, totalTotal);
			}
		});

		baseYear2.addValueChangeListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				setRequestTotal(baseFields, baseTotal);
				setYearSum(new TextField[] { baseYear2, rncYear2 }, totalYear2);
				setSum(totalLables, totalTotal);
			}
		});

		baseYear3.addValueChangeListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				setRequestTotal(baseFields, baseTotal);
				setYearSum(new TextField[] { baseYear3, rncYear3 }, totalYear3);
				setSum(totalLables, totalTotal);
			}
		});

		baseYear4.addValueChangeListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				setRequestTotal(baseFields, baseTotal);
				setYearSum(new TextField[] { baseYear4, rncYear4 }, totalYear4);
				setSum(totalLables, totalTotal);
			}
		});

		basePost.addValueChangeListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				setRequestTotal(baseFields, baseTotal);
				setYearSum(new TextField[] { basePost, rncPost }, totalPost);
				setSum(totalLables, totalTotal);
			}
		});

		rncPrior.addValueChangeListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				setRequestTotal(rncFields, rncTotal);
				setYearSum(new TextField[] { basePrior, rncPrior }, totalPrior);
				setSum(totalLables, totalTotal);
			}
		});

		rncCurrent.addValueChangeListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				setRequestTotal(rncFields, rncTotal);
				setYearSum(new TextField[] { baseCurrent, rncCurrent }, totalCurrent);
				setSum(totalLables, totalTotal);
			}
		});

		rncYear1.addValueChangeListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				setRequestTotal(rncFields, rncTotal);
				setYearSum(new TextField[] { baseYear1, rncYear1 }, totalYear1);
				setSum(totalLables, totalTotal);
			}
		});

		rncYear2.addValueChangeListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				setRequestTotal(rncFields, rncTotal);
				setYearSum(new TextField[] { baseYear2, rncYear2 }, totalYear2);
				setSum(totalLables, totalTotal);
			}
		});

		rncYear3.addValueChangeListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				setRequestTotal(rncFields, rncTotal);
				setYearSum(new TextField[] { baseYear3, rncYear3 }, totalYear3);
				setSum(totalLables, totalTotal);
			}
		});

		rncYear4.addValueChangeListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				setRequestTotal(rncFields, rncTotal);
				setYearSum(new TextField[] { baseYear4, rncYear4 }, totalYear4);
				setSum(totalLables, totalTotal);
			}
		});

		rncPost.addValueChangeListener(new ValueChangeListener() {

			@Override
			public void valueChange(ValueChangeEvent event) {
				setRequestTotal(rncFields, rncTotal);
				setYearSum(new TextField[] { basePost, rncPost }, totalPost);
				setSum(totalLables, totalTotal);
			}
		});

		for (int i = 0; i < req0Fields.length; i++) {
			req0Fields[i].addValueChangeListener(new ValueChangeListener() {

				@Override
				public void valueChange(ValueChangeEvent event) {
					setRequestTotal(req0Fields, req0Total);
				}
			});
		}

		for (int i = 0; i < req1Fields.length; i++) {
			req1Fields[i].addValueChangeListener(new ValueChangeListener() {

				@Override
				public void valueChange(ValueChangeEvent event) {
					setRequestTotal(req1Fields, req1Total);
				}
			});
		}

		for (int i = 0; i < req2Fields.length; i++) {
			req2Fields[i].addValueChangeListener(new ValueChangeListener() {

				@Override
				public void valueChange(ValueChangeEvent event) {
					setRequestTotal(req2Fields, req2Total);
				}
			});
		}
	}

	private void setRequestTotal(TextField[] fields, Label totalLabel) {
		double total = 0;
		for (int i = 0; i < fields.length; i++) {
			String value = fields[i].getValue();
			if (null != value && !"".equals(value)) {
				try {
					total += NumberToBigDecimalConverter.nf.parse(value).doubleValue();
				} catch (ParseException e) {
					e.printStackTrace();
				}
			}
		}
		totalLabel.setValue(NumberToBigDecimalConverter.nf.format(total));
	}

	private void setYearSum(TextField[] fields, Label sumLabel) {
		double sum = 0;
		for (int i = 0; i < fields.length; i++) {
			String value = fields[i].getValue();
			if (null != value && !"".equals(value)) {
				try {
					sum += NumberToBigDecimalConverter.nf.parse(value).doubleValue();
				} catch (ParseException e) {
					e.printStackTrace();
				}
			}
		}
		sumLabel.setValue(NumberToBigDecimalConverter.nf.format(sum));
	}

	private void setSum(Label[] fields, Label sumLabel) {
		double sum = 0;
		for (int i = 0; i < fields.length; i++) {
			String value = fields[i].getValue();
			if (null != value && !"".equals(value)) {
				try {
					sum += NumberToBigDecimalConverter.nf.parse(value).doubleValue();
				} catch (ParseException e) {
					e.printStackTrace();
				}
			}
		}
		sumLabel.setValue(NumberToBigDecimalConverter.nf.format(sum));
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("770px");
		mainLayout.setHeight("320px");

		// top-level component properties
		setWidth("770px");
		setHeight("320px");

		// labelPrototype
		labelPrototype = new Label();
		labelPrototype.setStyleName("prototype2");
		labelPrototype.setImmediate(false);
		labelPrototype.setWidth("-1px");
		labelPrototype.setHeight("-1px");
		labelPrototype.setValue("Label");
		mainLayout.addComponent(labelPrototype, "top:0.0px;right:0.0px;");

		// desc1
		desc1 = new TextArea();
		desc1.setImmediate(false);
		desc1.setWidth("600px");
		desc1.setHeight("100px");
		mainLayout.addComponent(desc1, "top:20.0px;left:20.0px;");

		// label_Millions
		label_Millions = new Label();
		label_Millions.setImmediate(false);
		label_Millions.setWidth("100px");
		label_Millions.setHeight("20px");
		label_Millions.setValue("$ Millions");
		mainLayout.addComponent(label_Millions, "top:140.0px;left:20.0px;");

		// label_base
		label_base = new Label();
		label_base.setImmediate(false);
		label_base.setWidth("120px");
		label_base.setHeight("20px");
		label_base.setValue("Base");
		mainLayout.addComponent(label_base, "top:160.0px;left:20.0px;");

		// label_RnC
		label_RnC = new Label();
		label_RnC.setImmediate(false);
		label_RnC.setWidth("120px");
		label_RnC.setHeight("20px");
		label_RnC.setValue("Risk & Contingency");
		mainLayout.addComponent(label_RnC, "top:180.0px;left:20.0px;");

		// label_TotalProject
		label_TotalProject = new Label();
		label_TotalProject.setImmediate(false);
		label_TotalProject.setWidth("120px");
		label_TotalProject.setHeight("20px");
		label_TotalProject.setValue("Total Project");
		mainLayout.addComponent(label_TotalProject, "top:200.0px;left:20.0px;");

		// label_Request0
		label_Request0 = new Label();
		label_Request0.setImmediate(false);
		label_Request0.setWidth("-1px");
		label_Request0.setHeight("20px");
		label_Request0.setValue("Current Request");
		mainLayout.addComponent(label_Request0, "top:220.0px;left:20.0px;");

		// label_Request1
		label_Request1 = new Label();
		label_Request1.setImmediate(false);
		label_Request1.setWidth("-1px");
		label_Request1.setHeight("20px");
		label_Request1.setValue("Request Date");
		mainLayout.addComponent(label_Request1, "top:240.0px;left:20.0px;");

		// label_Request2
		label_Request2 = new Label();
		label_Request2.setImmediate(false);
		label_Request2.setWidth("-1px");
		label_Request2.setHeight("20px");
		label_Request2.setValue("Request Date");
		mainLayout.addComponent(label_Request2, "top:260.0px;left:20.0px;");

		// label_Prior
		label_Prior = new Label();
		label_Prior.setImmediate(false);
		label_Prior.setWidth("60px");
		label_Prior.setHeight("20px");
		label_Prior.setValue("Prior");
		mainLayout.addComponent(label_Prior, "top:140.0px;left:200.0px;");

		// yearCurrent
		yearCurrent = new TextField();
		yearCurrent.setCaption("Current");
		yearCurrent.setImmediate(false);
		yearCurrent.setWidth("60px");
		yearCurrent.setHeight("20px");
		mainLayout.addComponent(yearCurrent, "top:140.0px;left:260.0px;");

		// year1
		year1 = new TextField();
		year1.setCaption("Year 1");
		year1.setImmediate(false);
		year1.setWidth("60px");
		year1.setHeight("20px");
		mainLayout.addComponent(year1, "top:140.0px;left:320.0px;");

		// year2
		year2 = new TextField();
		year2.setCaption("Year2");
		year2.setImmediate(false);
		year2.setWidth("60px");
		year2.setHeight("20px");
		mainLayout.addComponent(year2, "top:140.0px;left:380.0px;");

		// year3
		year3 = new TextField();
		year3.setCaption("Year3");
		year3.setImmediate(false);
		year3.setWidth("60px");
		year3.setHeight("20px");
		mainLayout.addComponent(year3, "top:140.0px;left:440.0px;");

		// year4
		year4 = new TextField();
		year4.setCaption("Year4");
		year4.setImmediate(false);
		year4.setWidth("60px");
		year4.setHeight("20px");
		mainLayout.addComponent(year4, "top:140.0px;left:500.0px;");

		// yearPost
		yearPost = new TextField();
		yearPost.setCaption("PostYear");
		yearPost.setImmediate(false);
		yearPost.setWidth("80px");
		yearPost.setHeight("20px");
		mainLayout.addComponent(yearPost, "top:140.0px;left:560.0px;");

		// label_Total
		label_Total = new Label();
		label_Total.setImmediate(false);
		label_Total.setWidth("60px");
		label_Total.setHeight("-1px");
		label_Total.setValue("Total");
		mainLayout.addComponent(label_Total, "top:142.0px;left:640.0px;");

		// label_Auth
		label_Auth = new Label();
		label_Auth.setImmediate(false);
		label_Auth.setWidth("60px");
		label_Auth.setHeight("20px");
		label_Auth.setValue("Auth");
		mainLayout.addComponent(label_Auth, "top:140.0px;left:700.0px;");

		// basePrior
		basePrior = new TextField();
		basePrior.setImmediate(true);
		basePrior.setWidth("60px");
		basePrior.setHeight("20px");
		mainLayout.addComponent(basePrior, "top:160.0px;left:200.0px;");

		// baseCurrent
		baseCurrent = new TextField();
		baseCurrent.setImmediate(true);
		baseCurrent.setWidth("60px");
		baseCurrent.setHeight("20px");
		mainLayout.addComponent(baseCurrent, "top:160.0px;left:260.0px;");

		// baseYear1
		baseYear1 = new TextField();
		baseYear1.setImmediate(true);
		baseYear1.setWidth("60px");
		baseYear1.setHeight("20px");
		mainLayout.addComponent(baseYear1, "top:160.0px;left:320.0px;");

		// baseYear2
		baseYear2 = new TextField();
		baseYear2.setImmediate(true);
		baseYear2.setWidth("60px");
		baseYear2.setHeight("20px");
		mainLayout.addComponent(baseYear2, "top:160.0px;left:380.0px;");

		// baseYear3
		baseYear3 = new TextField();
		baseYear3.setImmediate(true);
		baseYear3.setWidth("60px");
		baseYear3.setHeight("20px");
		mainLayout.addComponent(baseYear3, "top:160.0px;left:440.0px;");

		// baseYear4
		baseYear4 = new TextField();
		baseYear4.setImmediate(true);
		baseYear4.setWidth("60px");
		baseYear4.setHeight("20px");
		mainLayout.addComponent(baseYear4, "top:160.0px;left:500.0px;");

		// basePost
		basePost = new TextField();
		basePost.setImmediate(true);
		basePost.setWidth("80px");
		basePost.setHeight("20px");
		mainLayout.addComponent(basePost, "top:160.0px;left:560.0px;");

		// baseTotal
		baseTotal = new Label();
		baseTotal.setImmediate(false);
		baseTotal.setWidth("60px");
		baseTotal.setHeight("20px");
		baseTotal.setValue("0");
		mainLayout.addComponent(baseTotal, "top:160.0px;left:640.0px;");

		// rncPrior
		rncPrior = new TextField();
		rncPrior.setImmediate(true);
		rncPrior.setWidth("60px");
		rncPrior.setHeight("20px");
		mainLayout.addComponent(rncPrior, "top:180.0px;left:200.0px;");

		// rncCurrent
		rncCurrent = new TextField();
		rncCurrent.setImmediate(true);
		rncCurrent.setWidth("60px");
		rncCurrent.setHeight("20px");
		mainLayout.addComponent(rncCurrent, "top:180.0px;left:260.0px;");

		// rncYear1
		rncYear1 = new TextField();
		rncYear1.setImmediate(true);
		rncYear1.setWidth("60px");
		rncYear1.setHeight("20px");
		mainLayout.addComponent(rncYear1, "top:180.0px;left:320.0px;");

		// rncYear2
		rncYear2 = new TextField();
		rncYear2.setImmediate(true);
		rncYear2.setWidth("60px");
		rncYear2.setHeight("20px");
		mainLayout.addComponent(rncYear2, "top:180.0px;left:380.0px;");

		// rncYear3
		rncYear3 = new TextField();
		rncYear3.setImmediate(true);
		rncYear3.setWidth("60px");
		rncYear3.setHeight("20px");
		mainLayout.addComponent(rncYear3, "top:180.0px;left:440.0px;");

		// rncYear4
		rncYear4 = new TextField();
		rncYear4.setImmediate(true);
		rncYear4.setWidth("60px");
		rncYear4.setHeight("20px");
		mainLayout.addComponent(rncYear4, "top:180.0px;left:500.0px;");

		// rncPost
		rncPost = new TextField();
		rncPost.setImmediate(true);
		rncPost.setWidth("80px");
		rncPost.setHeight("20px");
		mainLayout.addComponent(rncPost, "top:180.0px;left:560.0px;");

		// rncTotal
		rncTotal = new Label();
		rncTotal.setImmediate(false);
		rncTotal.setWidth("60px");
		rncTotal.setHeight("20px");
		rncTotal.setValue("0");
		mainLayout.addComponent(rncTotal, "top:180.0px;left:640.0px;");

		// dateTotal
		dateTotal = new PopupDateField();
		dateTotal.setImmediate(false);
		dateTotal.setWidth("80px");
		dateTotal.setHeight("20px");
		mainLayout.addComponent(dateTotal, "top:200.0px;left:120.0px;");

		// totalPrior
		totalPrior = new Label();
		totalPrior.setImmediate(false);
		totalPrior.setWidth("60px");
		totalPrior.setHeight("20px");
		totalPrior.setValue("0");
		mainLayout.addComponent(totalPrior, "top:200.0px;left:200.0px;");

		// totalCurrent
		totalCurrent = new Label();
		totalCurrent.setImmediate(false);
		totalCurrent.setWidth("60px");
		totalCurrent.setHeight("20px");
		totalCurrent.setValue("0");
		mainLayout.addComponent(totalCurrent, "top:200.0px;left:260.0px;");

		// totalYear1
		totalYear1 = new Label();
		totalYear1.setImmediate(false);
		totalYear1.setWidth("60px");
		totalYear1.setHeight("20px");
		totalYear1.setValue("0");
		mainLayout.addComponent(totalYear1, "top:200.0px;left:320.0px;");

		// totalYear2
		totalYear2 = new Label();
		totalYear2.setImmediate(false);
		totalYear2.setWidth("60px");
		totalYear2.setHeight("20px");
		totalYear2.setValue("0");
		mainLayout.addComponent(totalYear2, "top:200.0px;left:380.0px;");

		// totalYear3
		totalYear3 = new Label();
		totalYear3.setImmediate(false);
		totalYear3.setWidth("60px");
		totalYear3.setHeight("20px");
		totalYear3.setValue("0");
		mainLayout.addComponent(totalYear3, "top:200.0px;left:440.0px;");

		// totalYear4
		totalYear4 = new Label();
		totalYear4.setImmediate(false);
		totalYear4.setWidth("60px");
		totalYear4.setHeight("20px");
		totalYear4.setValue("0");
		mainLayout.addComponent(totalYear4, "top:200.0px;left:500.0px;");

		// totalPost
		totalPost = new Label();
		totalPost.setImmediate(false);
		totalPost.setWidth("80px");
		totalPost.setHeight("20px");
		totalPost.setValue("0");
		mainLayout.addComponent(totalPost, "top:200.0px;left:560.0px;");

		// totalTotal
		totalTotal = new Label();
		totalTotal.setImmediate(false);
		totalTotal.setWidth("60px");
		totalTotal.setHeight("20px");
		totalTotal.setValue("0");
		mainLayout.addComponent(totalTotal, "top:200.0px;left:640.0px;");

		// dateReq0
		dateReq0 = new PopupDateField();
		dateReq0.setImmediate(false);
		dateReq0.setWidth("80px");
		dateReq0.setHeight("20px");
		mainLayout.addComponent(dateReq0, "top:220.0px;left:120.0px;");

		// req0Prior
		req0Prior = new TextField();
		req0Prior.setImmediate(true);
		req0Prior.setWidth("60px");
		req0Prior.setHeight("20px");
		mainLayout.addComponent(req0Prior, "top:220.0px;left:200.0px;");

		// req0Current
		req0Current = new TextField();
		req0Current.setImmediate(true);
		req0Current.setWidth("60px");
		req0Current.setHeight("20px");
		mainLayout.addComponent(req0Current, "top:220.0px;left:260.0px;");

		// req0Year1
		req0Year1 = new TextField();
		req0Year1.setImmediate(true);
		req0Year1.setWidth("60px");
		req0Year1.setHeight("20px");
		mainLayout.addComponent(req0Year1, "top:220.0px;left:320.0px;");

		// req0Year2
		req0Year2 = new TextField();
		req0Year2.setImmediate(true);
		req0Year2.setWidth("60px");
		req0Year2.setHeight("20px");
		mainLayout.addComponent(req0Year2, "top:220.0px;left:380.0px;");

		// req0Year3
		req0Year3 = new TextField();
		req0Year3.setImmediate(true);
		req0Year3.setWidth("60px");
		req0Year3.setHeight("20px");
		mainLayout.addComponent(req0Year3, "top:220.0px;left:440.0px;");

		// req0Year4
		req0Year4 = new TextField();
		req0Year4.setImmediate(true);
		req0Year4.setWidth("60px");
		req0Year4.setHeight("20px");
		mainLayout.addComponent(req0Year4, "top:220.0px;left:500.0px;");

		// req0Post
		req0Post = new TextField();
		req0Post.setImmediate(true);
		req0Post.setWidth("80px");
		req0Post.setHeight("20px");
		mainLayout.addComponent(req0Post, "top:220.0px;left:560.0px;");

		// req0Total
		req0Total = new Label();
		req0Total.setImmediate(false);
		req0Total.setWidth("60px");
		req0Total.setHeight("20px");
		req0Total.setValue("0");
		mainLayout.addComponent(req0Total, "top:220.0px;left:640.0px;");

		// req0Auth
		req0Auth = new TextField();
		req0Auth.setImmediate(false);
		req0Auth.setWidth("60px");
		req0Auth.setHeight("20px");
		mainLayout.addComponent(req0Auth, "top:220.0px;left:700.0px;");

		// dateReq1
		dateReq1 = new PopupDateField();
		dateReq1.setImmediate(false);
		dateReq1.setWidth("80px");
		dateReq1.setHeight("20px");
		mainLayout.addComponent(dateReq1, "top:240.0px;left:120.0px;");

		// req1Prior
		req1Prior = new TextField();
		req1Prior.setImmediate(true);
		req1Prior.setWidth("60px");
		req1Prior.setHeight("20px");
		mainLayout.addComponent(req1Prior, "top:240.0px;left:200.0px;");

		// req1Current
		req1Current = new TextField();
		req1Current.setImmediate(true);
		req1Current.setWidth("60px");
		req1Current.setHeight("20px");
		mainLayout.addComponent(req1Current, "top:240.0px;left:260.0px;");

		// req1Year1
		req1Year1 = new TextField();
		req1Year1.setImmediate(true);
		req1Year1.setWidth("60px");
		req1Year1.setHeight("20px");
		mainLayout.addComponent(req1Year1, "top:240.0px;left:320.0px;");

		// req1Year2
		req1Year2 = new TextField();
		req1Year2.setImmediate(true);
		req1Year2.setWidth("60px");
		req1Year2.setHeight("20px");
		mainLayout.addComponent(req1Year2, "top:240.0px;left:380.0px;");

		// req1Year3
		req1Year3 = new TextField();
		req1Year3.setImmediate(true);
		req1Year3.setWidth("60px");
		req1Year3.setHeight("20px");
		mainLayout.addComponent(req1Year3, "top:240.0px;left:440.0px;");

		// req1Year4
		req1Year4 = new TextField();
		req1Year4.setImmediate(true);
		req1Year4.setWidth("60px");
		req1Year4.setHeight("20px");
		mainLayout.addComponent(req1Year4, "top:240.0px;left:500.0px;");

		// req1Post
		req1Post = new TextField();
		req1Post.setImmediate(true);
		req1Post.setWidth("80px");
		req1Post.setHeight("20px");
		mainLayout.addComponent(req1Post, "top:240.0px;left:560.0px;");

		// req1Total
		req1Total = new Label();
		req1Total.setImmediate(false);
		req1Total.setWidth("60px");
		req1Total.setHeight("20px");
		req1Total.setValue("0");
		mainLayout.addComponent(req1Total, "top:240.0px;left:640.0px;");

		// req1Auth
		req1Auth = new TextField();
		req1Auth.setImmediate(false);
		req1Auth.setWidth("60px");
		req1Auth.setHeight("20px");
		mainLayout.addComponent(req1Auth, "top:240.0px;left:700.0px;");

		// dateReq2
		dateReq2 = new PopupDateField();
		dateReq2.setImmediate(false);
		dateReq2.setWidth("80px");
		dateReq2.setHeight("20px");
		mainLayout.addComponent(dateReq2, "top:260.0px;left:120.0px;");

		// req2Prior
		req2Prior = new TextField();
		req2Prior.setImmediate(true);
		req2Prior.setWidth("60px");
		req2Prior.setHeight("20px");
		mainLayout.addComponent(req2Prior, "top:260.0px;left:200.0px;");

		// req2Current
		req2Current = new TextField();
		req2Current.setImmediate(true);
		req2Current.setWidth("60px");
		req2Current.setHeight("20px");
		mainLayout.addComponent(req2Current, "top:260.0px;left:260.0px;");

		// req2Year1
		req2Year1 = new TextField();
		req2Year1.setImmediate(true);
		req2Year1.setWidth("60px");
		req2Year1.setHeight("20px");
		mainLayout.addComponent(req2Year1, "top:260.0px;left:320.0px;");

		// req2Year2
		req2Year2 = new TextField();
		req2Year2.setImmediate(true);
		req2Year2.setWidth("60px");
		req2Year2.setHeight("20px");
		mainLayout.addComponent(req2Year2, "top:260.0px;left:380.0px;");

		// req2Year3
		req2Year3 = new TextField();
		req2Year3.setImmediate(true);
		req2Year3.setWidth("60px");
		req2Year3.setHeight("20px");
		mainLayout.addComponent(req2Year3, "top:260.0px;left:440.0px;");

		// req2Year4
		req2Year4 = new TextField();
		req2Year4.setImmediate(true);
		req2Year4.setWidth("60px");
		req2Year4.setHeight("20px");
		mainLayout.addComponent(req2Year4, "top:260.0px;left:500.0px;");

		// req2Post
		req2Post = new TextField();
		req2Post.setImmediate(true);
		req2Post.setWidth("80px");
		req2Post.setHeight("20px");
		mainLayout.addComponent(req2Post, "top:260.0px;left:560.0px;");

		// req2Total
		req2Total = new Label();
		req2Total.setImmediate(false);
		req2Total.setWidth("60px");
		req2Total.setHeight("20px");
		req2Total.setValue("0");
		mainLayout.addComponent(req2Total, "top:260.0px;left:640.0px;");

		// req2Auth
		req2Auth = new TextField();
		req2Auth.setImmediate(false);
		req2Auth.setWidth("60px");
		req2Auth.setHeight("20px");
		mainLayout.addComponent(req2Auth, "top:260.0px;left:700.0px;");

		// label_targetBudget
		label_targetBudget = new Label();
		label_targetBudget.setImmediate(false);
		label_targetBudget.setWidth("-1px");
		label_targetBudget.setHeight("20px");
		label_targetBudget.setValue("Target Budget");
		mainLayout.addComponent(label_targetBudget, "top:280.0px;left:20.0px;");

		// targetBudget
		targetBudget = new TextField();
		targetBudget.setImmediate(false);
		targetBudget.setWidth("100px");
		targetBudget.setHeight("20px");
		mainLayout.addComponent(targetBudget, "top:280.0px;left:620.0px;");

		return mainLayout;
	}

}
