package com.pma.mpsr;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;

@SuppressWarnings("serial")
public class Form_1 extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TextArea textArea_1;
	@AutoGenerated
	private Label labelPrototype;

	String caption;
	String fieldProperty;
	FieldGroup fieldGroup = new FieldGroup();

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public Form_1(String caption, String fieldProperty) {
		this.caption = caption;
		this.fieldProperty = fieldProperty;

		buildMainLayout();
		setCompositionRoot(mainLayout);

		initFields();
	}

	private void initFields() {

		textArea_1.setCaption(caption);
		textArea_1.setNullRepresentation("");

		labelPrototype.setValue("Prototype");

		fieldGroup.bind(textArea_1, fieldProperty);
		fieldGroup.setBuffered(false);
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("640px");
		mainLayout.setHeight("440px");

		// top-level component properties
		setWidth("640px");
		setHeight("440px");

		// labelPrototype
		labelPrototype = new Label();
		labelPrototype.setStyleName("prototype2");
		labelPrototype.setImmediate(false);
		labelPrototype.setWidth("-1px");
		labelPrototype.setHeight("-1px");
		mainLayout.addComponent(labelPrototype, "top:0.0px;right:0.0px;");

		// textArea_1
		textArea_1 = new TextArea();
		textArea_1.setImmediate(false);
		textArea_1.setWidth("600px");
		textArea_1.setHeight("400px");
		mainLayout.addComponent(textArea_1, "top:20.0px;left:20.0px;");

		return mainLayout;
	}

}
