drop table MPSR if exists!
CREATE TABLE MPSR (
	MPSR_ID INTEGER IDENTITY,
	VERSION INTEGER DEFAULT 0,
	PROJ_DEF VARCHAR(20),
	PROJ_TITLE VARCHAR(200),
	RPT_MONTH_YEAR VARCHAR(20),
	PM VARCHAR(50),
	DIR VARCHAR(50),
	FILE_NAME VARCHAR(100)
)!
drop table MPSR_APDX if exists!
CREATE TABLE MPSR_APDX (
	MPSR_APDX_ID INTEGER IDENTITY,	
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	NUM VARCHAR(10),
	TITLE VARCHAR(255),
	FILE_NAME VARCHAR(255),
	DESC_1 VARCHAR(4000)
)!
drop table MPSR_APPR_CO if exists!
CREATE TABLE MPSR_APPR_CO (
	MPSR_APPR_CO_ID INTEGER IDENTITY,
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	PO_NUM VARCHAR(20),
	VENDOR VARCHAR(50),
	PREV_AMT DECIMAL(28,6),
	CURR_AMT DECIMAL(28,6),
	CURR_DESC VARCHAR(500),
	TOTAL_AMT DECIMAL(28,6)
)!
drop table MPSR_ATCH if exists!
CREATE TABLE MPSR_ATCH (
	MPSR_ATCH_ID INTEGER IDENTITY,
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	NUM VARCHAR(10),
	TITLE VARCHAR(255),
	FILE_NAME VARCHAR(255),
	DESC_1 VARCHAR(4000)
)!
drop table MPSR_AUTH if exists!
CREATE TABLE MPSR_AUTH (
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	DESC1 VARCHAR(4000),
	HEADER_YR0 VARCHAR(20),
	HEADER_YR1 VARCHAR(20),
	HEADER_YR2 VARCHAR(20),
	HEADER_YR3 VARCHAR(20),
	HEADER_YR4 VARCHAR(20),
	HEADER_POST_YEAR VARCHAR(20),
	BASE_PRIOR_YEAR DECIMAL(28,6),
	BASE_YR0 DECIMAL(28,6),
	BASE_YR1 DECIMAL(28,6),
	BASE_YR2 DECIMAL(28,6),
	BASE_YR3 DECIMAL(28,6),
	BASE_YR4 DECIMAL(28,6),
	BASE_POST_YEAR DECIMAL(28,6),
	RC_PRIOR_YEAR DECIMAL(28,6),
	RC_YR0 DECIMAL(28,6),
	RC_YR1 DECIMAL(28,6),
	RC_YR2 DECIMAL(28,6),
	RC_YR3 DECIMAL(28,6),
	RC_YR4 DECIMAL(28,6),
	RC_POST_YEAR DECIMAL(28,6),
	TOTAL_DATE TIMESTAMP,
	REQ0_PRIOR_YEAR DECIMAL(28,6),
	REQ0_YR0 DECIMAL(28,6),
	REQ0_YR1 DECIMAL(28,6),
	REQ0_YR2 DECIMAL(28,6),
	REQ0_YR3 DECIMAL(28,6),
	REQ0_YR4 DECIMAL(28,6),
	REQ0_POST_YEAR DECIMAL(28,6),
	REQ0_DATE TIMESTAMP,
	REQ1_PRIOR_YEAR DECIMAL(28,6),
	REQ1_YR0 DECIMAL(28,6),
	REQ1_YR1 DECIMAL(28,6),
	REQ1_YR2 DECIMAL(28,6),
	REQ1_YR3 DECIMAL(28,6),
	REQ1_YR4 DECIMAL(28,6),
	REQ1_POST_YEAR DECIMAL(28,6),
	REQ1_DATE TIMESTAMP,
	REQ2_PRIOR_YEAR DECIMAL(28,6),
	REQ2_YR0 DECIMAL(28,6),
	REQ2_YR1 DECIMAL(28,6),
	REQ2_YR2 DECIMAL(28,6),
	REQ2_YR3 DECIMAL(28,6),
	REQ2_YR4 DECIMAL(28,6),
	REQ2_POST_YEAR DECIMAL(28,6),
	REQ2_DATE TIMESTAMP,
	TARGETBUDGET VARCHAR(20),
	REQ0_AUTH DECIMAL(28,6),
	REQ1_AUTH DECIMAL(28,6),
	REQ2_AUTH DECIMAL(28,6),
	primary key (MPSR_ID)
)!
drop table MPSR_BUDGET if exists!
CREATE TABLE MPSR_BUDGET (
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	DESC1 VARCHAR(4000),
	PM_BUDGET DECIMAL(28,6),
	PM_ACT DECIMAL(28,6),
	PM_COMMIT DECIMAL(28,6),
	PM_OTHER DECIMAL(28,6),
	IP_ENG_BUDGET DECIMAL(28,6),
	IP_ENG_ACT DECIMAL(28,6),
	IP_ENG_COMMIT DECIMAL(28,6),
	IP_ENG_OTHER DECIMAL(28,6),
	IP_LP_BUDGET DECIMAL(28,6),
	IP_LP_ACT DECIMAL(28,6),
	IP_LP_COMMIT DECIMAL(28,6),
	IP_LP_OTHER DECIMAL(28,6),
	IP_LAND_BUDGET DECIMAL(28,6),
	IP_LAND_ACT DECIMAL(28,6),
	IP_LAND_COMMIT DECIMAL(28,6),
	IP_LAND_OTHER DECIMAL(28,6),
	IP_STR_BUDGET DECIMAL(28,6),
	IP_STR_ACT DECIMAL(28,6),
	IP_STR_COMMIT DECIMAL(28,6),
	IP_STR_OTHER DECIMAL(28,6),
	IP_STA_BUDGET DECIMAL(28,6),
	IP_STA_ACT DECIMAL(28,6),
	IP_STA_COMMIT DECIMAL(28,6),
	IP_STA_OTHER DECIMAL(28,6),
	IP_CIV_BUDGET DECIMAL(28,6),
	IP_CIV_ACT DECIMAL(28,6),
	IP_CIV_COMMIT DECIMAL(28,6),
	IP_CIV_OTHER DECIMAL(28,6),
	IP_ELE_BUDGET DECIMAL(28,6),
	IP_ELE_ACT DECIMAL(28,6),
	IP_ELE_COMMIT DECIMAL(28,6),
	IP_ELE_OTHER DECIMAL(28,6),
	OP_ENG_BUDGET DECIMAL(28,6),
	OP_ENG_ACT DECIMAL(28,6),
	OP_ENG_COMMIT DECIMAL(28,6),
	OP_ENG_OTHER DECIMAL(28,6),
	OP_PCURE_BUDGET DECIMAL(28,6),
	OP_PCURE_ACT DECIMAL(28,6),
	OP_PCURE_COMMIT DECIMAL(28,6),
	OP_PCURE_OTHER DECIMAL(28,6),
	OP_CSTRUC_BUDGET DECIMAL(28,6),
	OP_CSTRUC_ACT DECIMAL(28,6),
	OP_CSTRUC_COMMIT DECIMAL(28,6),
	OP_CSTRUC_OTHER DECIMAL(28,6),
	SALV_BUDGET DECIMAL(28,6),
	SALV_ACT DECIMAL(28,6),
	SALV_COMMIT DECIMAL(28,6),
	SALV_OTHER DECIMAL(28,6),
	WDRAW_BUDGET DECIMAL(28,6),
	WDRAW_ACT DECIMAL(28,6),
	WDRAW_COMMIT DECIMAL(28,6),
	WDRAW_OTHER DECIMAL(28,6),
	RISK_BUDGET DECIMAL(28,6),
	RISK_ACT DECIMAL(28,6),
	RISK_COMMIT DECIMAL(28,6),
	RISK_OTHER DECIMAL(28,6),
	primary key (MPSR_ID)
)!
drop table MPSR_CONST_IP if exists!
CREATE TABLE MPSR_CONST_IP (
	MPSR_CONST_IP_ID INTEGER IDENTITY,	
	MPSR_ID INTEGER,	
	VERSION INTEGER DEFAULT 0,
	FIGURE VARCHAR(10),
	TITLE VARCHAR(200),
	WORK VARCHAR(100),
	DESCRIPTION VARCHAR(4000),
	FILE_NAME VARCHAR(100)
)!
drop table MPSR_CONST_OP if exists!
CREATE TABLE MPSR_CONST_OP (
	MPSR_CONST_OP_ID INTEGER IDENTITY,
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	FIGURE VARCHAR(10),
	TITLE VARCHAR(200),
	WORK VARCHAR(100),
	DESCRIPTION VARCHAR(4000),
	FILE_NAME VARCHAR(100)
)!
drop table MPSR_COST_PERF if exists!
CREATE TABLE MPSR_COST_PERF (
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	FILE_NAME VARCHAR(100),
	primary key (MPSR_ID)
)!
drop table MPSR_COST_RPT if exists!
CREATE TABLE MPSR_COST_RPT (
	MPSR_COST_RPT_ID INTEGER IDENTITY,	
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	WBS VARCHAR(20) NOT NULL,
	WBS_DESC VARCHAR(100),
	EST DECIMAL(28,6),
	ACT DECIMAL(28,6),
	EAC DECIMAL(28,6)
)!
drop table MPSR_ENG_IP if exists!
CREATE TABLE MPSR_ENG_IP (
	MPSR_ENG_IP_ID INTEGER IDENTITY,
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	PACKAGE VARCHAR(50),
	IFR VARCHAR(50),
	IFC VARCHAR(50),
	INDICATOR VARCHAR(10),
	NOTE VARCHAR(500)
)!
drop table MPSR_ENG_OP if exists!
CREATE TABLE MPSR_ENG_OP (
	MPSR_ENG_OP_ID INTEGER IDENTITY,	
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	PACKAGE VARCHAR(50),
	IFR VARCHAR(50),
	IFC VARCHAR(50),
	INDICATOR VARCHAR(10),
	NOTE VARCHAR(500)
)!
drop table MPSR_EXE_SUM if exists!
CREATE TABLE MPSR_EXE_SUM (
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	DESC_1_1_1 VARCHAR(4000),
	DESC_1_1_2 VARCHAR(4000),
	DESC_1_1_3 VARCHAR(4000),
	DESC_1_1_4 VARCHAR(4000),
	DESC_1_3_1 VARCHAR(4000),
	DESC_1_3_2 VARCHAR(4000),
	primary key (MPSR_ID)
)!
drop table MPSR_FUNC_PERF if exists!
CREATE TABLE MPSR_FUNC_PERF (
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	PROJ_STATUS VARCHAR(10),
	PROJ_TREND VARCHAR(10),
	PROJ_COMMENT VARCHAR(1000),
	SAFETY_STATUS VARCHAR(10),
	SAFETY_TREND VARCHAR(10),
	SAFETY_COMMENT VARCHAR(1000),
	LICEN_STATUS VARCHAR(10),
	LICEN_TREND VARCHAR(10),
	LICEN_COMMENT VARCHAR(1000),
	CORP_STATUS VARCHAR(10),
	CORP_TREND VARCHAR(10),
	CORP_COMMENT VARCHAR(1000),
	IPDE_STATUS VARCHAR(10),
	IPDE_TREND VARCHAR(10),
	IPDE_COMMENT VARCHAR(1000),
	OUTREACH_STATUS VARCHAR(10),
	OUTREACH_TREND VARCHAR(10),
	OUTREACH_COMMENT VARCHAR(1000),
	PROCU_STATUS VARCHAR(10),
	PROCU_TREND VARCHAR(2010),
	PROCU_COMMENT VARCHAR(1000),
	CONST_STATUS VARCHAR(10),
	CONST_TREND VARCHAR(10),
	CONST_COMMENT VARCHAR(1000),
	ENV_STATUS VARCHAR(10),
	ENV_TREND VARCHAR(10),
	ENV_COMMENT VARCHAR(1000),
	SALV_STATUS VARCHAR(10),
	SALV_TREND VARCHAR(10),
	SALV_COMMENT VARCHAR(1000),
	WITHDRAW_STATUS VARCHAR(10),
	WITHDRAW_TREND VARCHAR(10),
	WITHDRAW_COMMENT VARCHAR(1000),
	PROJ_PCT DECIMAL(4,3),
	SAFETY_PCT DECIMAL(4,3),
	LICEN_PCT DECIMAL(4,3),
	CORP_PCT DECIMAL(4,3),
	IPDE_PCT DECIMAL(4,3),
	OUTREACH_PCT DECIMAL(4,3),
	PROCU_PCT DECIMAL(4,3),
	CONST_PCT DECIMAL(4,3),
	ENV_PCT DECIMAL(4,3),
	SALV_PCT DECIMAL(4,3),
	WITHDRAW_PCT DECIMAL(4,3),
	TARGET_BUDGET_STATUS VARCHAR(10),
	TARGET_BUDGET_TREND VARCHAR(10),
	TARGET_BUDGET_COMMENT VARCHAR(1000),
	TARGET_BUDGET_PCT DECIMAL(4,3),
	primary key (MPSR_ID)
)!
drop table MPSR_LPE if exists!
CREATE TABLE MPSR_LPE (
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	DESC_6_1 VARCHAR(4000),
	DESC_6_2_1 VARCHAR(4000),
	DESC_6_2_2 VARCHAR(4000),
	primary key (MPSR_ID)
)!
drop table MPSR_MILESTONE if exists!
CREATE TABLE MPSR_MILESTONE (
	MPSR_MILESTONE_ID INTEGER IDENTITY,
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	MILESTONE VARCHAR(100),
	PLAN_DATE TIMESTAMP,
	END_DATE TIMESTAMP,
	MILESTONE_ID VARCHAR(20)
)!
drop table MPSR_PEND_CO if exists!
CREATE TABLE MPSR_PEND_CO (
	MPSR_PEND_CO_ID INTEGER IDENTITY,
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	PO_NUM VARCHAR(20),
	VENDOR VARCHAR(50),
	PREV_AMT DECIMAL(28,6),
	CURR_AMT DECIMAL(28,6),
	CURR_DESC VARCHAR(500),
	TOTAL_AMT DECIMAL(28,6)
)!
drop table MPSR_PROCURE if exists!
CREATE TABLE MPSR_PROCURE (
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	DESC_8_1_A VARCHAR(4000),
	DESC_8_1_B VARCHAR(4000),
	RECEIPT_TO_DATE DECIMAL(28,6),
	OPEN_COMMIT DECIMAL(28,6),
	DESC_8_2_1 VARCHAR(4000),
	DESC_8_2_2 VARCHAR(4000),
	primary key (MPSR_ID)
)!
drop table MPSR_SAFE if exists!
CREATE TABLE MPSR_SAFE (
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	DESC1 VARCHAR(4000),
	WH_CUR DECIMAL(28,6),
	WH_YTD DECIMAL(28,6),
	WH_PTD DECIMAL(28,6),
	OSHA_CUR DECIMAL(28,6),
	OSHA_YTD DECIMAL(28,6),
	OSHA_PTD DECIMAL(28,6),
	AID_1_CUR DECIMAL(28,6),
	AID_1_YTD DECIMAL(28,6),
	AID_1_PTD DECIMAL(28,6),
	MISS_CUR DECIMAL(28,6),
	MISS_YTD DECIMAL(28,6),
	MISS_PTD DECIMAL(28,6),
	AID_2_CUR DECIMAL(28,6),
	AID_2_YTD DECIMAL(28,6),
	AID_2_PTD DECIMAL(28,6),
	NOTE VARCHAR(1000),
	primary key (MPSR_ID)
)!
drop table MPSR_SCHEDULE if exists!
CREATE TABLE MPSR_SCHEDULE (
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	DESC_5_4 VARCHAR(4000),
	DESC_5_1 VARCHAR(4000),
	DESC_5_2 VARCHAR(4000),
	DESC_5_3 VARCHAR(4000),
	primary key (MPSR_ID)
)!
drop table MPSR_SCHE_PERF if exists!
CREATE TABLE MPSR_SCHE_PERF (
	MPSR_SCHE_PERF_ID INTEGER IDENTITY,
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	WBS VARCHAR(255),
	ORIGDUR DECIMAL(6,1),
	REMDUR DECIMAL(6,2),
	BL_PROJECT_START TIMESTAMP,
	BL_PROJECT_FINISH TIMESTAMP,
	START_DATE TIMESTAMP,
	FINISH_DATE TIMESTAMP,
	TOTAL_FLOAT DECIMAL(6,1),
	STATUS VARCHAR(20)
)!
drop table MPSR_STATUS_SUM if exists!
CREATE TABLE MPSR_STATUS_SUM (
	MPSR_ID INTEGER,
	VERSION INTEGER DEFAULT 0,
	BUDGET_STATUS VARCHAR(10),
	BUDGET_APPROVED DECIMAL(28,6),
	BUDGET_TO_DATE DECIMAL(28,6),
	BUDGET_AT_COMP DECIMAL(28,6),
	SCHEDULE_STATUS VARCHAR(10),
	SCHEDULE_APPROVED DECIMAL(28,6),
	SCHEDULE_TO_DATE DECIMAL(28,6),
	SCHEDULE_AT_COMP DECIMAL(28,6),
	IN_SERVICE_STATUS VARCHAR(10),
	IN_SERVICE_APPROVED TIMESTAMP,
	IN_SERVICE_TO_DATE TIMESTAMP,
	IN_SERVICE_AT_COMP TIMESTAMP,
	primary key (MPSR_ID)
)!