package com.kohmiho.mpsr;

import java.text.ParseException;

import com.kohmiho.vaadin.converter.NumberToBigDecimalConverter;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.data.fieldgroup.FieldGroup;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;

@SuppressWarnings("serial")
public class Form_4_0_0 extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private TextField total_EAC;
	@AutoGenerated
	private TextField total_ETC;
	@AutoGenerated
	private TextField total_AdditionalCost;
	@AutoGenerated
	private TextField total_Commit;
	@AutoGenerated
	private TextField total_Actual;
	@AutoGenerated
	private TextField total_Budget;
	@AutoGenerated
	private TextField risk_EAC;
	@AutoGenerated
	private TextField risk_ETC;
	@AutoGenerated
	private TextField risk_AdditionalCost;
	@AutoGenerated
	private TextField risk_Commit;
	@AutoGenerated
	private TextField risk_Actual;
	@AutoGenerated
	private TextField risk_Budget;
	@AutoGenerated
	private TextField subtotal_EAC;
	@AutoGenerated
	private TextField subtotal_ETC;
	@AutoGenerated
	private TextField subtotal_AdditionalCost;
	@AutoGenerated
	private TextField subtotal_Commit;
	@AutoGenerated
	private TextField subtotal_Actual;
	@AutoGenerated
	private TextField subtotal_Budget;
	@AutoGenerated
	private TextField withdraw_EAC;
	@AutoGenerated
	private TextField withdraw_ETC;
	@AutoGenerated
	private TextField withdraw_AdditionalCost;
	@AutoGenerated
	private TextField withdraw_Commit;
	@AutoGenerated
	private TextField withdraw_Actual;
	@AutoGenerated
	private TextField withdraw_Budget;
	@AutoGenerated
	private TextField salvage_EAC;
	@AutoGenerated
	private TextField salvage_ETC;
	@AutoGenerated
	private TextField salvage_AdditionalCost;
	@AutoGenerated
	private TextField salvage_Commit;
	@AutoGenerated
	private TextField salvage_Actual;
	@AutoGenerated
	private TextField salvage_Budget;
	@AutoGenerated
	private TextField op_Construction_EAC;
	@AutoGenerated
	private TextField op_Construction_ETC;
	@AutoGenerated
	private TextField op_Construction_AdditionalCost;
	@AutoGenerated
	private TextField op_Construction_Commit;
	@AutoGenerated
	private TextField op_Construction_Actual;
	@AutoGenerated
	private TextField op_Construction_Budget;
	@AutoGenerated
	private TextField op_Procure_EAC;
	@AutoGenerated
	private TextField op_Procure_ETC;
	@AutoGenerated
	private TextField op_Procure_AdditionalCost;
	@AutoGenerated
	private TextField op_Procure_Commit;
	@AutoGenerated
	private TextField op_Procure_Actual;
	@AutoGenerated
	private TextField op_Procure_Budget;
	@AutoGenerated
	private TextField op_Eng_EAC;
	@AutoGenerated
	private TextField op_Eng_ETC;
	@AutoGenerated
	private TextField op_Eng_AdditionalCost;
	@AutoGenerated
	private TextField op_Eng_Commit;
	@AutoGenerated
	private TextField op_Eng_Actual;
	@AutoGenerated
	private TextField op_Eng_Budget;
	@AutoGenerated
	private TextField op_EAC;
	@AutoGenerated
	private TextField op_ETC;
	@AutoGenerated
	private TextField op_AdditionalCost;
	@AutoGenerated
	private TextField op_Commit;
	@AutoGenerated
	private TextField op_Actual;
	@AutoGenerated
	private TextField op_Budget;
	@AutoGenerated
	private TextField ip_Electrical_EAC;
	@AutoGenerated
	private TextField ip_Electrical_ETC;
	@AutoGenerated
	private TextField ip_Electrical_AdditionalCost;
	@AutoGenerated
	private TextField ip_Electrical_Commit;
	@AutoGenerated
	private TextField ip_Electrical_Actual;
	@AutoGenerated
	private TextField ip_Electrical_Budget;
	@AutoGenerated
	private TextField ip_Civil_EAC;
	@AutoGenerated
	private TextField ip_Civil_ETC;
	@AutoGenerated
	private TextField ip_Civil_AdditionalCost;
	@AutoGenerated
	private TextField ip_Civil_Commit;
	@AutoGenerated
	private TextField ip_Civil_Actual;
	@AutoGenerated
	private TextField ip_Civil_Budget;
	@AutoGenerated
	private TextField ip_Construction_EAC;
	@AutoGenerated
	private TextField ip_Construction_ETC;
	@AutoGenerated
	private TextField ip_Construction_AdditionalCost;
	@AutoGenerated
	private TextField ip_Construction_Commit;
	@AutoGenerated
	private TextField ip_Construction_Actual;
	@AutoGenerated
	private TextField ip_Construction_Budget;
	@AutoGenerated
	private TextField ip_Station_EAC;
	@AutoGenerated
	private TextField ip_Station_ETC;
	@AutoGenerated
	private TextField ip_Station_AdditionalCost;
	@AutoGenerated
	private TextField ip_Station_Commit;
	@AutoGenerated
	private TextField ip_Station_Actual;
	@AutoGenerated
	private TextField ip_Station_Budget;
	@AutoGenerated
	private TextField ip_Structure_EAC;
	@AutoGenerated
	private TextField ip_Structure_ETC;
	@AutoGenerated
	private TextField ip_Structure_AdditionalCost;
	@AutoGenerated
	private TextField ip_Structure_Commit;
	@AutoGenerated
	private TextField ip_Structure_Actual;
	@AutoGenerated
	private TextField ip_Structure_Budget;
	@AutoGenerated
	private TextField ip_Land_EAC;
	@AutoGenerated
	private TextField ip_Land_ETC;
	@AutoGenerated
	private TextField ip_Land_AdditionalCost;
	@AutoGenerated
	private TextField ip_Land_Commit;
	@AutoGenerated
	private TextField ip_Land_Actual;
	@AutoGenerated
	private TextField ip_Land_Budget;
	@AutoGenerated
	private TextField ip_Procure_EAC;
	@AutoGenerated
	private TextField ip_Procure_ETC;
	@AutoGenerated
	private TextField ip_Procure_AdditionalCost;
	@AutoGenerated
	private TextField ip_Procure_Commit;
	@AutoGenerated
	private TextField ip_Procure_Actual;
	@AutoGenerated
	private TextField ip_Procure_Budget;
	@AutoGenerated
	private TextField ip_LP_EAC;
	@AutoGenerated
	private TextField ip_LP_ETC;
	@AutoGenerated
	private TextField ip_LP_AdditionalCost;
	@AutoGenerated
	private TextField ip_LP_Commit;
	@AutoGenerated
	private TextField ip_LP_Actual;
	@AutoGenerated
	private TextField ip_LP_Budget;
	@AutoGenerated
	private TextField ip_Eng_EAC;
	@AutoGenerated
	private TextField ip_Eng_ETC;
	@AutoGenerated
	private TextField ip_Eng_AdditionalCost;
	@AutoGenerated
	private TextField ip_Eng_Commit;
	@AutoGenerated
	private TextField ip_Eng_Actual;
	@AutoGenerated
	private TextField ip_Eng_Budget;
	@AutoGenerated
	private TextField ip_EAC;
	@AutoGenerated
	private TextField ip_ETC;
	@AutoGenerated
	private TextField ip_AdditionalCost;
	@AutoGenerated
	private TextField ip_Commit;
	@AutoGenerated
	private TextField ip_Actual;
	@AutoGenerated
	private TextField ip_Budget;
	@AutoGenerated
	private TextField pm_EAC;
	@AutoGenerated
	private TextField pm_ETC;
	@AutoGenerated
	private TextField pm_AdditionalCost;
	@AutoGenerated
	private TextField pm_Commit;
	@AutoGenerated
	private TextField pm_Actual;
	@AutoGenerated
	private TextField pm_Budget;
	@AutoGenerated
	private Label label_EAC;
	@AutoGenerated
	private Label label_ETC;
	@AutoGenerated
	private Label label_AdditonalCost;
	@AutoGenerated
	private Label label_Commit;
	@AutoGenerated
	private Label label_Actual;
	@AutoGenerated
	private Label label_Budget;
	@AutoGenerated
	private Label label_Total;
	@AutoGenerated
	private Label label_Risk;
	@AutoGenerated
	private Label label_Subtotal;
	@AutoGenerated
	private Label label_Withdraw;
	@AutoGenerated
	private Label label_Salvage;
	@AutoGenerated
	private Label label_OP_Construction;
	@AutoGenerated
	private Label label_OP_Procure;
	@AutoGenerated
	private Label label_OP_ENG;
	@AutoGenerated
	private Label label_OP;
	@AutoGenerated
	private Label label_Electrical;
	@AutoGenerated
	private Label label_Civil;
	@AutoGenerated
	private Label label_IP_Construction;
	@AutoGenerated
	private Label label_Station;
	@AutoGenerated
	private Label label_Structure;
	@AutoGenerated
	private Label label_Land;
	@AutoGenerated
	private Label label_IP_Procure;
	@AutoGenerated
	private Label label_IP_LP;
	@AutoGenerated
	private Label label_IP_ENG;
	@AutoGenerated
	private Label label_IP;
	@AutoGenerated
	private Label label_PM;
	@AutoGenerated
	private TextArea desc1;
	@AutoGenerated
	private Label labelPrototype;

	FieldGroup fieldGroup = new FieldGroup();
	NumberToBigDecimalConverter numberConverter = new NumberToBigDecimalConverter();

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public Form_4_0_0() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		initFields();
		initListeners();
	}

	private void initFields() {

		mainLayout.addStyleName("form-4");

		labelPrototype.setValue("Prototype");

		desc1.setCaption(MPSRUI.TREE_4);
		desc1.setNullRepresentation("");
		fieldGroup.bind(desc1, "DESC1");

		TextField[] budgets = { pm_Budget, ip_Eng_Budget, ip_LP_Budget, ip_Land_Budget, ip_Structure_Budget, ip_Station_Budget, ip_Civil_Budget,
				ip_Electrical_Budget, op_Eng_Budget, op_Procure_Budget, op_Construction_Budget, salvage_Budget, withdraw_Budget, risk_Budget };
		String[] fieldBudgets = { "PM_BUDGET", "IP_ENG_BUDGET", "IP_LP_BUDGET", "IP_LAND_BUDGET", "IP_STR_BUDGET", "IP_STA_BUDGET", "IP_CIV_BUDGET",
				"IP_ELE_BUDGET", "OP_ENG_BUDGET", "OP_PCURE_BUDGET", "OP_CSTRUC_BUDGET", "SALV_BUDGET", "WDRAW_BUDGET", "RISK_BUDGET" };
		for (int i = 0; i < budgets.length; i++) {
			fieldGroup.bind(budgets[i], fieldBudgets[i]);
			budgets[i].setNullRepresentation("-");
			budgets[i].setConverter(numberConverter);
		}

		TextField[] actuals = { pm_Actual, ip_Eng_Actual, ip_LP_Actual, ip_Land_Actual, ip_Structure_Actual, ip_Station_Actual, ip_Civil_Actual,
				ip_Electrical_Actual, op_Eng_Actual, op_Procure_Actual, op_Construction_Actual, salvage_Actual, withdraw_Actual, risk_Actual };
		String[] fieldActuals = { "PM_ACT", "IP_ENG_ACT", "IP_LP_ACT", "IP_LAND_ACT", "IP_STR_ACT", "IP_STA_ACT", "IP_CIV_ACT", "IP_ELE_ACT", "OP_ENG_ACT",
				"OP_PCURE_ACT", "OP_CSTRUC_ACT", "SALV_ACT", "WDRAW_ACT", "RISK_ACT" };
		for (int i = 0; i < actuals.length; i++) {
			fieldGroup.bind(actuals[i], fieldActuals[i]);
			actuals[i].setNullRepresentation("-");
			actuals[i].setConverter(numberConverter);
		}

		TextField[] commits = { pm_Commit, ip_Eng_Commit, ip_LP_Commit, ip_Land_Commit, ip_Structure_Commit, ip_Station_Commit, ip_Civil_Commit,
				ip_Electrical_Commit, op_Eng_Commit, op_Procure_Commit, op_Construction_Commit, salvage_Commit, withdraw_Commit, risk_Commit };
		String[] fieldCommits = { "PM_COMMIT", "IP_ENG_COMMIT", "IP_LP_COMMIT", "IP_LAND_COMMIT", "IP_STR_COMMIT", "IP_STA_COMMIT", "IP_CIV_COMMIT",
				"IP_ELE_COMMIT", "OP_ENG_COMMIT", "OP_PCURE_COMMIT", "OP_CSTRUC_COMMIT", "SALV_COMMIT", "WDRAW_COMMIT", "RISK_COMMIT" };
		for (int i = 0; i < commits.length; i++) {
			fieldGroup.bind(commits[i], fieldCommits[i]);
			commits[i].setNullRepresentation("-");
			commits[i].setConverter(numberConverter);
		}

		TextField[] additionalCosts = { pm_AdditionalCost, ip_Eng_AdditionalCost, ip_LP_AdditionalCost, ip_Land_AdditionalCost, ip_Structure_AdditionalCost,
				ip_Station_AdditionalCost, ip_Civil_AdditionalCost, ip_Electrical_AdditionalCost, op_Eng_AdditionalCost, op_Procure_AdditionalCost,
				op_Construction_AdditionalCost, salvage_AdditionalCost, withdraw_AdditionalCost, risk_AdditionalCost };
		String[] fieldAdditionalCosts = { "PM_OTHER", "IP_ENG_OTHER", "IP_LP_OTHER", "IP_LAND_OTHER", "IP_STR_OTHER", "IP_STA_OTHER", "IP_CIV_OTHER",
				"IP_ELE_OTHER", "OP_ENG_OTHER", "OP_PCURE_OTHER", "OP_CSTRUC_OTHER", "SALV_OTHER", "WDRAW_OTHER", "RISK_OTHER" };
		for (int i = 0; i < additionalCosts.length; i++) {
			fieldGroup.bind(additionalCosts[i], fieldAdditionalCosts[i]);
			additionalCosts[i].setNullRepresentation("-");
			additionalCosts[i].setConverter(numberConverter);
		}

		fieldGroup.setBuffered(false);
	}

	private void initListeners() {

		TextField[][] items = { { ip_Land_Budget, ip_Structure_Budget, ip_Station_Budget }, { ip_Land_Actual, ip_Structure_Actual, ip_Station_Actual },
				{ ip_Land_Commit, ip_Structure_Commit, ip_Station_Commit }, { ip_Land_AdditionalCost, ip_Structure_AdditionalCost, ip_Station_AdditionalCost } };
		TextField[] targets = { ip_Procure_Budget, ip_Procure_Actual, ip_Procure_Commit, ip_Procure_AdditionalCost };
		addSetTotalListener(items, targets);

		items = new TextField[][] { { ip_Civil_Budget, ip_Electrical_Budget }, { ip_Civil_Actual, ip_Electrical_Actual },
				{ ip_Civil_Commit, ip_Electrical_Commit }, { ip_Civil_AdditionalCost, ip_Electrical_AdditionalCost } };
		targets = new TextField[] { ip_Construction_Budget, ip_Construction_Actual, ip_Construction_Commit, ip_Construction_AdditionalCost };
		addSetTotalListener(items, targets);

		items = new TextField[][] { { op_Eng_Budget, op_Procure_Budget, op_Construction_Budget }, { op_Eng_Actual, op_Procure_Actual, op_Construction_Actual },
				{ op_Eng_Commit, op_Procure_Commit, op_Construction_Commit },
				{ op_Eng_AdditionalCost, op_Procure_AdditionalCost, op_Construction_AdditionalCost } };
		targets = new TextField[] { op_Budget, op_Actual, op_Commit, op_AdditionalCost };
		addSetTotalListener(items, targets);

		items = new TextField[][] { { ip_Eng_Budget, ip_LP_Budget, ip_Procure_Budget, ip_Construction_Budget },
				{ ip_Eng_Actual, ip_LP_Actual, ip_Procure_Actual, ip_Construction_Actual },
				{ ip_Eng_Commit, ip_LP_Commit, ip_Procure_Commit, ip_Construction_Commit },
				{ ip_Eng_AdditionalCost, ip_LP_AdditionalCost, ip_Procure_AdditionalCost, ip_Construction_AdditionalCost } };
		targets = new TextField[] { ip_Budget, ip_Actual, ip_Commit, ip_AdditionalCost };
		addSetTotalListener(items, targets);

		items = new TextField[][] { { pm_Budget, ip_Budget, op_Budget, salvage_Budget, withdraw_Budget },
				{ pm_Actual, ip_Actual, op_Actual, salvage_Actual, withdraw_Actual }, { pm_Commit, ip_Commit, op_Commit, salvage_Commit, withdraw_Commit },
				{ pm_AdditionalCost, ip_AdditionalCost, op_AdditionalCost, salvage_AdditionalCost, withdraw_AdditionalCost } };
		targets = new TextField[] { subtotal_Budget, subtotal_Actual, subtotal_Commit, subtotal_AdditionalCost };
		addSetTotalListener(items, targets);

		items = new TextField[][] { { subtotal_Budget, risk_Budget }, { subtotal_Actual, risk_Actual }, { subtotal_Commit, risk_Commit },
				{ subtotal_AdditionalCost, risk_AdditionalCost } };
		targets = new TextField[] { total_Budget, total_Actual, total_Commit, total_AdditionalCost };
		addSetTotalListener(items, targets);

		items = new TextField[][] { { pm_Commit, pm_AdditionalCost }, { ip_Commit, ip_AdditionalCost }, { ip_Eng_Commit, ip_Eng_AdditionalCost },
				{ ip_LP_Commit, ip_LP_AdditionalCost }, { ip_Procure_Commit, ip_Procure_AdditionalCost }, { ip_Land_Commit, ip_Land_AdditionalCost },
				{ ip_Structure_Commit, ip_Structure_AdditionalCost }, { ip_Station_Commit, ip_Station_AdditionalCost },
				{ ip_Construction_Commit, ip_Construction_AdditionalCost }, { ip_Civil_Commit, ip_Civil_AdditionalCost },
				{ ip_Electrical_Commit, ip_Electrical_AdditionalCost }, { op_Commit, op_AdditionalCost }, { op_Eng_Commit, op_Eng_AdditionalCost },
				{ op_Procure_Commit, op_Procure_AdditionalCost }, { op_Construction_Commit, op_Construction_AdditionalCost },
				{ salvage_Commit, salvage_AdditionalCost }, { withdraw_Commit, withdraw_AdditionalCost }, { subtotal_Commit, subtotal_AdditionalCost },
				{ risk_Commit, risk_AdditionalCost }, { total_Commit, total_AdditionalCost } };
		targets = new TextField[] { pm_ETC, ip_ETC, ip_Eng_ETC, ip_LP_ETC, ip_Procure_ETC, ip_Land_ETC, ip_Structure_ETC, ip_Station_ETC, ip_Construction_ETC,
				ip_Civil_ETC, ip_Electrical_ETC, op_ETC, op_Eng_ETC, op_Procure_ETC, op_Construction_ETC, salvage_ETC, withdraw_ETC, subtotal_ETC, risk_ETC,
				total_ETC };
		addSetTotalListener(items, targets);

		items = new TextField[][] { { pm_Actual, pm_ETC }, { ip_Actual, ip_ETC }, { ip_Eng_Actual, ip_Eng_ETC }, { ip_LP_Actual, ip_LP_ETC },
				{ ip_Procure_Actual, ip_Procure_ETC }, { ip_Land_Actual, ip_Land_ETC }, { ip_Structure_Actual, ip_Structure_ETC },
				{ ip_Station_Actual, ip_Station_ETC }, { ip_Construction_Actual, ip_Construction_ETC }, { ip_Civil_Actual, ip_Civil_ETC },
				{ ip_Electrical_Actual, ip_Electrical_ETC }, { op_Actual, op_ETC }, { op_Eng_Actual, op_Eng_ETC }, { op_Procure_Actual, op_Procure_ETC },
				{ op_Construction_Actual, op_Construction_ETC }, { salvage_Actual, salvage_ETC }, { withdraw_Actual, withdraw_ETC },
				{ subtotal_Actual, subtotal_ETC }, { risk_Actual, risk_ETC }, { total_Actual, total_ETC } };
		targets = new TextField[] { pm_EAC, ip_EAC, ip_Eng_EAC, ip_LP_EAC, ip_Procure_EAC, ip_Land_EAC, ip_Structure_EAC, ip_Station_EAC, ip_Construction_EAC,
				ip_Civil_EAC, ip_Electrical_EAC, op_EAC, op_Eng_EAC, op_Procure_EAC, op_Construction_EAC, salvage_EAC, withdraw_EAC, subtotal_EAC, risk_EAC,
				total_EAC };
		addSetTotalListener(items, targets);

	}

	private void addSetTotalListener(TextField[][] items, TextField[] targets) {
		for (int i = 0; i < items.length; i++) {
			final TextField[] children = items[i];
			final TextField parent = targets[i];
			for (int j = 0; j < items[i].length; j++) {
				items[i][j].addValueChangeListener(new ValueChangeListener() {
					@Override
					public void valueChange(ValueChangeEvent event) {
						setTotal(children, parent);
					}
				});
			}
		}
	}

	private void setTotal(TextField[] fields, TextField target) {
		double total = 0;
		for (int i = 0; i < fields.length; i++) {
			String value = fields[i].getValue();
			if (null != value && !"".equals(value)) {
				try {
					total += NumberToBigDecimalConverter.nf.parse(value).doubleValue();
				} catch (ParseException e) {
					e.printStackTrace();
				}
			}
		}
		target.setValue(NumberToBigDecimalConverter.nf.format(total));

	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("760px");
		mainLayout.setHeight("640px");

		// top-level component properties
		setWidth("760px");
		setHeight("640px");

		// labelPrototype
		labelPrototype = new Label();
		labelPrototype.setStyleName("prototype2");
		labelPrototype.setImmediate(false);
		labelPrototype.setWidth("-1px");
		labelPrototype.setHeight("-1px");
		labelPrototype.setValue("Label");
		mainLayout.addComponent(labelPrototype, "top:0.0px;right:0.0px;");

		// desc1
		desc1 = new TextArea();
		desc1.setImmediate(false);
		desc1.setWidth("600px");
		desc1.setHeight("100px");
		mainLayout.addComponent(desc1, "top:20.0px;left:20.0px;");

		// label_PM
		label_PM = new Label();
		label_PM.setImmediate(false);
		label_PM.setWidth("200px");
		label_PM.setHeight("20px");
		label_PM.setValue("Project Management");
		mainLayout.addComponent(label_PM, "top:220.0px;left:0.0px;");

		// label_IP
		label_IP = new Label();
		label_IP.setImmediate(false);
		label_IP.setWidth("200px");
		label_IP.setHeight("20px");
		label_IP.setValue("Inside Plant");
		mainLayout.addComponent(label_IP, "top:240.0px;left:0.0px;");

		// label_IP_ENG
		label_IP_ENG = new Label();
		label_IP_ENG.setImmediate(false);
		label_IP_ENG.setWidth("180px");
		label_IP_ENG.setHeight("20px");
		label_IP_ENG.setValue("Design & Engineering");
		mainLayout.addComponent(label_IP_ENG, "top:260.0px;left:20.0px;");

		// label_IP_LP
		label_IP_LP = new Label();
		label_IP_LP.setImmediate(false);
		label_IP_LP.setWidth("180px");
		label_IP_LP.setHeight("20px");
		label_IP_LP.setValue("Licensing & Permitting");
		mainLayout.addComponent(label_IP_LP, "top:280.0px;left:20.0px;");

		// label_IP_Procure
		label_IP_Procure = new Label();
		label_IP_Procure.setImmediate(false);
		label_IP_Procure.setWidth("180px");
		label_IP_Procure.setHeight("20px");
		label_IP_Procure.setValue("Procurement");
		mainLayout.addComponent(label_IP_Procure, "top:300.0px;left:20.0px;");

		// label_Land
		label_Land = new Label();
		label_Land.setImmediate(false);
		label_Land.setWidth("160px");
		label_Land.setHeight("20px");
		label_Land.setValue("Land & Land Rights");
		mainLayout.addComponent(label_Land, "top:320.0px;left:40.0px;");

		// label_Structure
		label_Structure = new Label();
		label_Structure.setImmediate(false);
		label_Structure.setWidth("160px");
		label_Structure.setHeight("20px");
		label_Structure.setValue("Structures & Improvements");
		mainLayout.addComponent(label_Structure, "top:340.0px;left:40.0px;");

		// label_Station
		label_Station = new Label();
		label_Station.setImmediate(false);
		label_Station.setWidth("160px");
		label_Station.setHeight("20px");
		label_Station.setValue("Station Equipment");
		mainLayout.addComponent(label_Station, "top:360.0px;left:40.0px;");

		// label_IP_Construction
		label_IP_Construction = new Label();
		label_IP_Construction.setImmediate(false);
		label_IP_Construction.setWidth("180px");
		label_IP_Construction.setHeight("20px");
		label_IP_Construction.setValue("Construction");
		mainLayout.addComponent(label_IP_Construction, "top:380.0px;left:20.0px;");

		// label_Civil
		label_Civil = new Label();
		label_Civil.setImmediate(false);
		label_Civil.setWidth("160px");
		label_Civil.setHeight("20px");
		label_Civil.setValue("Civil");
		mainLayout.addComponent(label_Civil, "top:400.0px;left:40.0px;");

		// label_Electrical
		label_Electrical = new Label();
		label_Electrical.setImmediate(false);
		label_Electrical.setWidth("160px");
		label_Electrical.setHeight("20px");
		label_Electrical.setValue("Electrical");
		mainLayout.addComponent(label_Electrical, "top:420.0px;left:40.0px;");

		// label_OP
		label_OP = new Label();
		label_OP.setImmediate(false);
		label_OP.setWidth("160px");
		label_OP.setHeight("20px");
		label_OP.setValue("Outside Plant");
		mainLayout.addComponent(label_OP, "top:440.0px;left:0.0px;");

		// label_OP_ENG
		label_OP_ENG = new Label();
		label_OP_ENG.setImmediate(false);
		label_OP_ENG.setWidth("180px");
		label_OP_ENG.setHeight("20px");
		label_OP_ENG.setValue("Design & Engineering");
		mainLayout.addComponent(label_OP_ENG, "top:460.0px;left:20.0px;");

		// label_OP_Procure
		label_OP_Procure = new Label();
		label_OP_Procure.setImmediate(false);
		label_OP_Procure.setWidth("180px");
		label_OP_Procure.setHeight("20px");
		label_OP_Procure.setValue("Procurement");
		mainLayout.addComponent(label_OP_Procure, "top:480.0px;left:20.0px;");

		// label_OP_Construction
		label_OP_Construction = new Label();
		label_OP_Construction.setImmediate(false);
		label_OP_Construction.setWidth("180px");
		label_OP_Construction.setHeight("20px");
		label_OP_Construction.setValue("Construction");
		mainLayout.addComponent(label_OP_Construction, "top:500.0px;left:20.0px;");

		// label_Salvage
		label_Salvage = new Label();
		label_Salvage.setImmediate(false);
		label_Salvage.setWidth("160px");
		label_Salvage.setHeight("20px");
		label_Salvage.setValue("Salvage");
		mainLayout.addComponent(label_Salvage, "top:520.0px;left:0.0px;");

		// label_Withdraw
		label_Withdraw = new Label();
		label_Withdraw.setImmediate(false);
		label_Withdraw.setWidth("160px");
		label_Withdraw.setHeight("20px");
		label_Withdraw.setValue("Withdrawal");
		mainLayout.addComponent(label_Withdraw, "top:540.0px;left:0.0px;");

		// label_Subtotal
		label_Subtotal = new Label();
		label_Subtotal.setImmediate(false);
		label_Subtotal.setWidth("160px");
		label_Subtotal.setHeight("20px");
		label_Subtotal.setValue("Subtotal");
		mainLayout.addComponent(label_Subtotal, "top:560.0px;left:0.0px;");

		// label_Risk
		label_Risk = new Label();
		label_Risk.setImmediate(false);
		label_Risk.setWidth("160px");
		label_Risk.setHeight("20px");
		label_Risk.setValue("Risk & Contingency");
		mainLayout.addComponent(label_Risk, "top:580.0px;left:0.0px;");

		// label_Total
		label_Total = new Label();
		label_Total.setImmediate(false);
		label_Total.setWidth("160px");
		label_Total.setHeight("20px");
		label_Total.setValue("Total Project");
		mainLayout.addComponent(label_Total, "top:600.0px;left:0.0px;");

		// label_Budget
		label_Budget = new Label();
		label_Budget.setImmediate(false);
		label_Budget.setWidth("90px");
		label_Budget.setHeight("20px");
		label_Budget.setValue("Project Budget");
		mainLayout.addComponent(label_Budget, "top:200.0px;left:220.0px;");

		// label_Actual
		label_Actual = new Label();
		label_Actual.setImmediate(false);
		label_Actual.setWidth("90px");
		label_Actual.setHeight("20px");
		label_Actual.setValue("Actual Cost");
		mainLayout.addComponent(label_Actual, "top:200.0px;left:310.0px;");

		// label_Commit
		label_Commit = new Label();
		label_Commit.setImmediate(false);
		label_Commit.setWidth("90px");
		label_Commit.setHeight("20px");
		label_Commit.setValue("Commitments");
		mainLayout.addComponent(label_Commit, "top:200.0px;left:400.0px;");

		// label_AdditonalCost
		label_AdditonalCost = new Label();
		label_AdditonalCost.setImmediate(false);
		label_AdditonalCost.setWidth("90px");
		label_AdditonalCost.setHeight("40px");
		label_AdditonalCost.setValue("Addition Cost to Completion");
		mainLayout.addComponent(label_AdditonalCost, "top:180.0px;left:490.0px;");

		// label_ETC
		label_ETC = new Label();
		label_ETC.setImmediate(false);
		label_ETC.setWidth("90px");
		label_ETC.setHeight("40px");
		label_ETC.setValue("Estimate to Completion");
		mainLayout.addComponent(label_ETC, "top:180.0px;left:580.0px;");

		// label_EAC
		label_EAC = new Label();
		label_EAC.setImmediate(false);
		label_EAC.setWidth("90px");
		label_EAC.setHeight("40px");
		label_EAC.setValue("Estimate At Completion");
		mainLayout.addComponent(label_EAC, "top:180.0px;left:670.0px;");

		// pm_Budget
		pm_Budget = new TextField();
		pm_Budget.setImmediate(true);
		pm_Budget.setWidth("90px");
		pm_Budget.setHeight("20px");
		mainLayout.addComponent(pm_Budget, "top:220.0px;left:220.0px;");

		// pm_Actual
		pm_Actual = new TextField();
		pm_Actual.setImmediate(true);
		pm_Actual.setWidth("90px");
		pm_Actual.setHeight("20px");
		pm_Actual.setValue("0");
		mainLayout.addComponent(pm_Actual, "top:220.0px;left:310.0px;");

		// pm_Commit
		pm_Commit = new TextField();
		pm_Commit.setImmediate(true);
		pm_Commit.setWidth("90px");
		pm_Commit.setHeight("20px");
		pm_Commit.setValue("0");
		mainLayout.addComponent(pm_Commit, "top:220.0px;left:400.0px;");

		// pm_AdditionalCost
		pm_AdditionalCost = new TextField();
		pm_AdditionalCost.setImmediate(true);
		pm_AdditionalCost.setWidth("90px");
		pm_AdditionalCost.setHeight("20px");
		mainLayout.addComponent(pm_AdditionalCost, "top:220.0px;left:490.0px;");

		// pm_ETC
		pm_ETC = new TextField();
		pm_ETC.setImmediate(true);
		pm_ETC.setWidth("90px");
		pm_ETC.setHeight("20px");
		pm_ETC.setValue("0");
		mainLayout.addComponent(pm_ETC, "top:220.0px;left:580.0px;");

		// pm_EAC
		pm_EAC = new TextField();
		pm_EAC.setImmediate(true);
		pm_EAC.setWidth("90px");
		pm_EAC.setHeight("20px");
		pm_EAC.setValue("0");
		mainLayout.addComponent(pm_EAC, "top:220.0px;left:670.0px;");

		// ip_Budget
		ip_Budget = new TextField();
		ip_Budget.setImmediate(true);
		ip_Budget.setWidth("90px");
		ip_Budget.setHeight("20px");
		ip_Budget.setValue("0");
		mainLayout.addComponent(ip_Budget, "top:240.0px;left:220.0px;");

		// ip_Actual
		ip_Actual = new TextField();
		ip_Actual.setImmediate(true);
		ip_Actual.setWidth("90px");
		ip_Actual.setHeight("20px");
		ip_Actual.setValue("0");
		mainLayout.addComponent(ip_Actual, "top:240.0px;left:310.0px;");

		// ip_Commit
		ip_Commit = new TextField();
		ip_Commit.setImmediate(true);
		ip_Commit.setWidth("90px");
		ip_Commit.setHeight("20px");
		ip_Commit.setValue("0");
		mainLayout.addComponent(ip_Commit, "top:240.0px;left:400.0px;");

		// ip_AdditionalCost
		ip_AdditionalCost = new TextField();
		ip_AdditionalCost.setImmediate(true);
		ip_AdditionalCost.setWidth("90px");
		ip_AdditionalCost.setHeight("20px");
		ip_AdditionalCost.setValue("0");
		mainLayout.addComponent(ip_AdditionalCost, "top:240.0px;left:490.0px;");

		// ip_ETC
		ip_ETC = new TextField();
		ip_ETC.setImmediate(true);
		ip_ETC.setWidth("90px");
		ip_ETC.setHeight("20px");
		ip_ETC.setValue("0");
		mainLayout.addComponent(ip_ETC, "top:240.0px;left:580.0px;");

		// ip_EAC
		ip_EAC = new TextField();
		ip_EAC.setImmediate(true);
		ip_EAC.setWidth("90px");
		ip_EAC.setHeight("20px");
		ip_EAC.setValue("0");
		mainLayout.addComponent(ip_EAC, "top:240.0px;left:670.0px;");

		// ip_Eng_Budget
		ip_Eng_Budget = new TextField();
		ip_Eng_Budget.setImmediate(true);
		ip_Eng_Budget.setWidth("90px");
		ip_Eng_Budget.setHeight("20px");
		mainLayout.addComponent(ip_Eng_Budget, "top:260.0px;left:220.0px;");

		// ip_Eng_Actual
		ip_Eng_Actual = new TextField();
		ip_Eng_Actual.setImmediate(true);
		ip_Eng_Actual.setWidth("90px");
		ip_Eng_Actual.setHeight("20px");
		ip_Eng_Actual.setValue("0");
		mainLayout.addComponent(ip_Eng_Actual, "top:260.0px;left:310.0px;");

		// ip_Eng_Commit
		ip_Eng_Commit = new TextField();
		ip_Eng_Commit.setImmediate(true);
		ip_Eng_Commit.setWidth("90px");
		ip_Eng_Commit.setHeight("20px");
		ip_Eng_Commit.setValue("0");
		mainLayout.addComponent(ip_Eng_Commit, "top:260.0px;left:400.0px;");

		// ip_Eng_AdditionalCost
		ip_Eng_AdditionalCost = new TextField();
		ip_Eng_AdditionalCost.setImmediate(true);
		ip_Eng_AdditionalCost.setWidth("90px");
		ip_Eng_AdditionalCost.setHeight("20px");
		mainLayout.addComponent(ip_Eng_AdditionalCost, "top:260.0px;left:490.0px;");

		// ip_Eng_ETC
		ip_Eng_ETC = new TextField();
		ip_Eng_ETC.setImmediate(true);
		ip_Eng_ETC.setWidth("90px");
		ip_Eng_ETC.setHeight("20px");
		ip_Eng_ETC.setValue("0");
		mainLayout.addComponent(ip_Eng_ETC, "top:260.0px;left:580.0px;");

		// ip_Eng_EAC
		ip_Eng_EAC = new TextField();
		ip_Eng_EAC.setImmediate(true);
		ip_Eng_EAC.setWidth("90px");
		ip_Eng_EAC.setHeight("20px");
		ip_Eng_EAC.setValue("0");
		mainLayout.addComponent(ip_Eng_EAC, "top:260.0px;left:670.0px;");

		// ip_LP_Budget
		ip_LP_Budget = new TextField();
		ip_LP_Budget.setImmediate(true);
		ip_LP_Budget.setWidth("90px");
		ip_LP_Budget.setHeight("20px");
		mainLayout.addComponent(ip_LP_Budget, "top:280.0px;left:220.0px;");

		// ip_LP_Actual
		ip_LP_Actual = new TextField();
		ip_LP_Actual.setImmediate(true);
		ip_LP_Actual.setWidth("90px");
		ip_LP_Actual.setHeight("20px");
		ip_LP_Actual.setValue("0");
		mainLayout.addComponent(ip_LP_Actual, "top:280.0px;left:310.0px;");

		// ip_LP_Commit
		ip_LP_Commit = new TextField();
		ip_LP_Commit.setImmediate(true);
		ip_LP_Commit.setWidth("90px");
		ip_LP_Commit.setHeight("20px");
		ip_LP_Commit.setValue("0");
		mainLayout.addComponent(ip_LP_Commit, "top:280.0px;left:400.0px;");

		// ip_LP_AdditionalCost
		ip_LP_AdditionalCost = new TextField();
		ip_LP_AdditionalCost.setImmediate(true);
		ip_LP_AdditionalCost.setWidth("90px");
		ip_LP_AdditionalCost.setHeight("20px");
		mainLayout.addComponent(ip_LP_AdditionalCost, "top:280.0px;left:490.0px;");

		// ip_LP_ETC
		ip_LP_ETC = new TextField();
		ip_LP_ETC.setImmediate(true);
		ip_LP_ETC.setWidth("90px");
		ip_LP_ETC.setHeight("20px");
		ip_LP_ETC.setValue("0");
		mainLayout.addComponent(ip_LP_ETC, "top:280.0px;left:580.0px;");

		// ip_LP_EAC
		ip_LP_EAC = new TextField();
		ip_LP_EAC.setImmediate(true);
		ip_LP_EAC.setWidth("90px");
		ip_LP_EAC.setHeight("20px");
		ip_LP_EAC.setValue("0");
		mainLayout.addComponent(ip_LP_EAC, "top:280.0px;left:670.0px;");

		// ip_Procure_Budget
		ip_Procure_Budget = new TextField();
		ip_Procure_Budget.setImmediate(true);
		ip_Procure_Budget.setWidth("90px");
		ip_Procure_Budget.setHeight("20px");
		ip_Procure_Budget.setValue("0");
		mainLayout.addComponent(ip_Procure_Budget, "top:300.0px;left:220.0px;");

		// ip_Procure_Actual
		ip_Procure_Actual = new TextField();
		ip_Procure_Actual.setImmediate(true);
		ip_Procure_Actual.setWidth("90px");
		ip_Procure_Actual.setHeight("20px");
		ip_Procure_Actual.setValue("0");
		mainLayout.addComponent(ip_Procure_Actual, "top:300.0px;left:310.0px;");

		// ip_Procure_Commit
		ip_Procure_Commit = new TextField();
		ip_Procure_Commit.setImmediate(true);
		ip_Procure_Commit.setWidth("90px");
		ip_Procure_Commit.setHeight("20px");
		ip_Procure_Commit.setValue("0");
		mainLayout.addComponent(ip_Procure_Commit, "top:300.0px;left:400.0px;");

		// ip_Procure_AdditionalCost
		ip_Procure_AdditionalCost = new TextField();
		ip_Procure_AdditionalCost.setImmediate(true);
		ip_Procure_AdditionalCost.setWidth("90px");
		ip_Procure_AdditionalCost.setHeight("20px");
		ip_Procure_AdditionalCost.setValue("0");
		mainLayout.addComponent(ip_Procure_AdditionalCost, "top:300.0px;left:490.0px;");

		// ip_Procure_ETC
		ip_Procure_ETC = new TextField();
		ip_Procure_ETC.setImmediate(true);
		ip_Procure_ETC.setWidth("90px");
		ip_Procure_ETC.setHeight("20px");
		ip_Procure_ETC.setValue("0");
		mainLayout.addComponent(ip_Procure_ETC, "top:300.0px;left:580.0px;");

		// ip_Procure_EAC
		ip_Procure_EAC = new TextField();
		ip_Procure_EAC.setImmediate(true);
		ip_Procure_EAC.setWidth("90px");
		ip_Procure_EAC.setHeight("20px");
		ip_Procure_EAC.setValue("0");
		mainLayout.addComponent(ip_Procure_EAC, "top:300.0px;left:670.0px;");

		// ip_Land_Budget
		ip_Land_Budget = new TextField();
		ip_Land_Budget.setImmediate(true);
		ip_Land_Budget.setWidth("90px");
		ip_Land_Budget.setHeight("20px");
		mainLayout.addComponent(ip_Land_Budget, "top:320.0px;left:220.0px;");

		// ip_land_Actual
		ip_Land_Actual = new TextField();
		ip_Land_Actual.setImmediate(true);
		ip_Land_Actual.setWidth("90px");
		ip_Land_Actual.setHeight("20px");
		ip_Land_Actual.setValue("0");
		mainLayout.addComponent(ip_Land_Actual, "top:320.0px;left:310.0px;");

		// ip_Land_Commit
		ip_Land_Commit = new TextField();
		ip_Land_Commit.setImmediate(true);
		ip_Land_Commit.setWidth("90px");
		ip_Land_Commit.setHeight("20px");
		ip_Land_Commit.setValue("0");
		mainLayout.addComponent(ip_Land_Commit, "top:320.0px;left:400.0px;");

		// ip_Land_AdditionalCost
		ip_Land_AdditionalCost = new TextField();
		ip_Land_AdditionalCost.setImmediate(true);
		ip_Land_AdditionalCost.setWidth("90px");
		ip_Land_AdditionalCost.setHeight("20px");
		mainLayout.addComponent(ip_Land_AdditionalCost, "top:320.0px;left:490.0px;");

		// ip_Land_ETC
		ip_Land_ETC = new TextField();
		ip_Land_ETC.setImmediate(true);
		ip_Land_ETC.setWidth("90px");
		ip_Land_ETC.setHeight("20px");
		ip_Land_ETC.setValue("0");
		mainLayout.addComponent(ip_Land_ETC, "top:320.0px;left:580.0px;");

		// ip_Land_EAC
		ip_Land_EAC = new TextField();
		ip_Land_EAC.setImmediate(true);
		ip_Land_EAC.setWidth("90px");
		ip_Land_EAC.setHeight("20px");
		ip_Land_EAC.setValue("0");
		mainLayout.addComponent(ip_Land_EAC, "top:320.0px;left:670.0px;");

		// ip_Structure_Budget
		ip_Structure_Budget = new TextField();
		ip_Structure_Budget.setImmediate(true);
		ip_Structure_Budget.setWidth("90px");
		ip_Structure_Budget.setHeight("20px");
		mainLayout.addComponent(ip_Structure_Budget, "top:340.0px;left:220.0px;");

		// ip_Structure_Actual
		ip_Structure_Actual = new TextField();
		ip_Structure_Actual.setImmediate(true);
		ip_Structure_Actual.setWidth("90px");
		ip_Structure_Actual.setHeight("20px");
		ip_Structure_Actual.setValue("0");
		mainLayout.addComponent(ip_Structure_Actual, "top:340.0px;left:310.0px;");

		// ip_Structure_Commit
		ip_Structure_Commit = new TextField();
		ip_Structure_Commit.setImmediate(true);
		ip_Structure_Commit.setWidth("90px");
		ip_Structure_Commit.setHeight("20px");
		ip_Structure_Commit.setValue("0");
		mainLayout.addComponent(ip_Structure_Commit, "top:340.0px;left:400.0px;");

		// ip_Structure_AdditionalCost
		ip_Structure_AdditionalCost = new TextField();
		ip_Structure_AdditionalCost.setImmediate(true);
		ip_Structure_AdditionalCost.setWidth("90px");
		ip_Structure_AdditionalCost.setHeight("20px");
		mainLayout.addComponent(ip_Structure_AdditionalCost, "top:340.0px;left:490.0px;");

		// ip_Structure_ETC
		ip_Structure_ETC = new TextField();
		ip_Structure_ETC.setImmediate(true);
		ip_Structure_ETC.setWidth("90px");
		ip_Structure_ETC.setHeight("20px");
		ip_Structure_ETC.setValue("0");
		mainLayout.addComponent(ip_Structure_ETC, "top:340.0px;left:580.0px;");

		// ip_Structure_EAC
		ip_Structure_EAC = new TextField();
		ip_Structure_EAC.setImmediate(true);
		ip_Structure_EAC.setWidth("90px");
		ip_Structure_EAC.setHeight("20px");
		ip_Structure_EAC.setValue("0");
		mainLayout.addComponent(ip_Structure_EAC, "top:340.0px;left:670.0px;");

		// ip_Station_Budget
		ip_Station_Budget = new TextField();
		ip_Station_Budget.setImmediate(true);
		ip_Station_Budget.setWidth("90px");
		ip_Station_Budget.setHeight("20px");
		mainLayout.addComponent(ip_Station_Budget, "top:360.0px;left:220.0px;");

		// ip_Station_Actual
		ip_Station_Actual = new TextField();
		ip_Station_Actual.setImmediate(true);
		ip_Station_Actual.setWidth("90px");
		ip_Station_Actual.setHeight("20px");
		ip_Station_Actual.setValue("0");
		mainLayout.addComponent(ip_Station_Actual, "top:360.0px;left:310.0px;");

		// ip_Station_Commit
		ip_Station_Commit = new TextField();
		ip_Station_Commit.setImmediate(true);
		ip_Station_Commit.setWidth("90px");
		ip_Station_Commit.setHeight("20px");
		ip_Station_Commit.setValue("0");
		mainLayout.addComponent(ip_Station_Commit, "top:360.0px;left:400.0px;");

		// ip_Station_AdditionalCost
		ip_Station_AdditionalCost = new TextField();
		ip_Station_AdditionalCost.setImmediate(true);
		ip_Station_AdditionalCost.setWidth("90px");
		ip_Station_AdditionalCost.setHeight("20px");
		mainLayout.addComponent(ip_Station_AdditionalCost, "top:360.0px;left:490.0px;");

		// ip_Station_ETC
		ip_Station_ETC = new TextField();
		ip_Station_ETC.setImmediate(true);
		ip_Station_ETC.setWidth("90px");
		ip_Station_ETC.setHeight("20px");
		ip_Station_ETC.setValue("0");
		mainLayout.addComponent(ip_Station_ETC, "top:360.0px;left:580.0px;");

		// ip_Station_EAC
		ip_Station_EAC = new TextField();
		ip_Station_EAC.setImmediate(true);
		ip_Station_EAC.setWidth("90px");
		ip_Station_EAC.setHeight("20px");
		ip_Station_EAC.setValue("0");
		mainLayout.addComponent(ip_Station_EAC, "top:360.0px;left:670.0px;");

		// ip_Construction_Budget
		ip_Construction_Budget = new TextField();
		ip_Construction_Budget.setImmediate(true);
		ip_Construction_Budget.setWidth("90px");
		ip_Construction_Budget.setHeight("20px");
		ip_Construction_Budget.setValue("0");
		mainLayout.addComponent(ip_Construction_Budget, "top:380.0px;left:220.0px;");

		// ip_Construction_Actual
		ip_Construction_Actual = new TextField();
		ip_Construction_Actual.setImmediate(true);
		ip_Construction_Actual.setWidth("90px");
		ip_Construction_Actual.setHeight("20px");
		ip_Construction_Actual.setValue("0");
		mainLayout.addComponent(ip_Construction_Actual, "top:380.0px;left:310.0px;");

		// ip_Construction_Commit
		ip_Construction_Commit = new TextField();
		ip_Construction_Commit.setImmediate(true);
		ip_Construction_Commit.setWidth("90px");
		ip_Construction_Commit.setHeight("20px");
		ip_Construction_Commit.setValue("0");
		mainLayout.addComponent(ip_Construction_Commit, "top:380.0px;left:400.0px;");

		// ip_Construction_AdditionalCost
		ip_Construction_AdditionalCost = new TextField();
		ip_Construction_AdditionalCost.setImmediate(true);
		ip_Construction_AdditionalCost.setWidth("90px");
		ip_Construction_AdditionalCost.setHeight("20px");
		ip_Construction_AdditionalCost.setValue("0");
		mainLayout.addComponent(ip_Construction_AdditionalCost, "top:380.0px;left:490.0px;");

		// ip_Construction_ETC
		ip_Construction_ETC = new TextField();
		ip_Construction_ETC.setImmediate(true);
		ip_Construction_ETC.setWidth("90px");
		ip_Construction_ETC.setHeight("20px");
		ip_Construction_ETC.setValue("0");
		mainLayout.addComponent(ip_Construction_ETC, "top:380.0px;left:580.0px;");

		// ip_Construction_EAC
		ip_Construction_EAC = new TextField();
		ip_Construction_EAC.setImmediate(true);
		ip_Construction_EAC.setWidth("90px");
		ip_Construction_EAC.setHeight("20px");
		ip_Construction_EAC.setValue("0");
		mainLayout.addComponent(ip_Construction_EAC, "top:380.0px;left:670.0px;");

		// ip_Civil_Budget
		ip_Civil_Budget = new TextField();
		ip_Civil_Budget.setImmediate(true);
		ip_Civil_Budget.setWidth("90px");
		ip_Civil_Budget.setHeight("20px");
		mainLayout.addComponent(ip_Civil_Budget, "top:400.0px;left:220.0px;");

		// ip_Civil_Actual
		ip_Civil_Actual = new TextField();
		ip_Civil_Actual.setImmediate(true);
		ip_Civil_Actual.setWidth("90px");
		ip_Civil_Actual.setHeight("20px");
		ip_Civil_Actual.setValue("0");
		mainLayout.addComponent(ip_Civil_Actual, "top:400.0px;left:310.0px;");

		// ip_Civil_Commit
		ip_Civil_Commit = new TextField();
		ip_Civil_Commit.setImmediate(true);
		ip_Civil_Commit.setWidth("90px");
		ip_Civil_Commit.setHeight("20px");
		ip_Civil_Commit.setValue("0");
		mainLayout.addComponent(ip_Civil_Commit, "top:400.0px;left:400.0px;");

		// ip_Civil_AdditionalCost
		ip_Civil_AdditionalCost = new TextField();
		ip_Civil_AdditionalCost.setImmediate(true);
		ip_Civil_AdditionalCost.setWidth("90px");
		ip_Civil_AdditionalCost.setHeight("20px");
		mainLayout.addComponent(ip_Civil_AdditionalCost, "top:400.0px;left:490.0px;");

		// ip_Civil_ETC
		ip_Civil_ETC = new TextField();
		ip_Civil_ETC.setImmediate(true);
		ip_Civil_ETC.setWidth("90px");
		ip_Civil_ETC.setHeight("20px");
		ip_Civil_ETC.setValue("0");
		mainLayout.addComponent(ip_Civil_ETC, "top:400.0px;left:580.0px;");

		// ip_Civil_EAC
		ip_Civil_EAC = new TextField();
		ip_Civil_EAC.setImmediate(true);
		ip_Civil_EAC.setWidth("90px");
		ip_Civil_EAC.setHeight("20px");
		ip_Civil_EAC.setValue("0");
		mainLayout.addComponent(ip_Civil_EAC, "top:400.0px;left:670.0px;");

		// ip_Electrical_Budget
		ip_Electrical_Budget = new TextField();
		ip_Electrical_Budget.setImmediate(true);
		ip_Electrical_Budget.setWidth("90px");
		ip_Electrical_Budget.setHeight("20px");
		mainLayout.addComponent(ip_Electrical_Budget, "top:420.0px;left:220.0px;");

		// ip_Electrical_Actual
		ip_Electrical_Actual = new TextField();
		ip_Electrical_Actual.setImmediate(true);
		ip_Electrical_Actual.setWidth("90px");
		ip_Electrical_Actual.setHeight("20px");
		ip_Electrical_Actual.setValue("0");
		mainLayout.addComponent(ip_Electrical_Actual, "top:420.0px;left:310.0px;");

		// ip_Electrical_Commit
		ip_Electrical_Commit = new TextField();
		ip_Electrical_Commit.setImmediate(true);
		ip_Electrical_Commit.setWidth("90px");
		ip_Electrical_Commit.setHeight("20px");
		ip_Electrical_Commit.setValue("0");
		mainLayout.addComponent(ip_Electrical_Commit, "top:420.0px;left:400.0px;");

		// ip_Electrical_AdditionalCost
		ip_Electrical_AdditionalCost = new TextField();
		ip_Electrical_AdditionalCost.setImmediate(true);
		ip_Electrical_AdditionalCost.setWidth("90px");
		ip_Electrical_AdditionalCost.setHeight("20px");
		mainLayout.addComponent(ip_Electrical_AdditionalCost, "top:420.0px;left:490.0px;");

		// ip_Electrical_ETC
		ip_Electrical_ETC = new TextField();
		ip_Electrical_ETC.setImmediate(true);
		ip_Electrical_ETC.setWidth("90px");
		ip_Electrical_ETC.setHeight("20px");
		ip_Electrical_ETC.setValue("0");
		mainLayout.addComponent(ip_Electrical_ETC, "top:420.0px;left:580.0px;");

		// ip_Electrical_EAC
		ip_Electrical_EAC = new TextField();
		ip_Electrical_EAC.setImmediate(true);
		ip_Electrical_EAC.setWidth("90px");
		ip_Electrical_EAC.setHeight("20px");
		ip_Electrical_EAC.setValue("0");
		mainLayout.addComponent(ip_Electrical_EAC, "top:420.0px;left:670.0px;");

		// op_Budget
		op_Budget = new TextField();
		op_Budget.setImmediate(true);
		op_Budget.setWidth("90px");
		op_Budget.setHeight("20px");
		op_Budget.setValue("0");
		mainLayout.addComponent(op_Budget, "top:440.0px;left:220.0px;");

		// op_Actual
		op_Actual = new TextField();
		op_Actual.setImmediate(true);
		op_Actual.setWidth("90px");
		op_Actual.setHeight("20px");
		op_Actual.setValue("0");
		mainLayout.addComponent(op_Actual, "top:440.0px;left:310.0px;");

		// op_Commit
		op_Commit = new TextField();
		op_Commit.setImmediate(true);
		op_Commit.setWidth("90px");
		op_Commit.setHeight("20px");
		op_Commit.setValue("0");
		mainLayout.addComponent(op_Commit, "top:440.0px;left:400.0px;");

		// op_AdditionalCost
		op_AdditionalCost = new TextField();
		op_AdditionalCost.setImmediate(true);
		op_AdditionalCost.setWidth("90px");
		op_AdditionalCost.setHeight("20px");
		op_AdditionalCost.setValue("0");
		mainLayout.addComponent(op_AdditionalCost, "top:440.0px;left:490.0px;");

		// op_ETC
		op_ETC = new TextField();
		op_ETC.setImmediate(true);
		op_ETC.setWidth("90px");
		op_ETC.setHeight("20px");
		op_ETC.setValue("0");
		mainLayout.addComponent(op_ETC, "top:440.0px;left:580.0px;");

		// op_EAC
		op_EAC = new TextField();
		op_EAC.setImmediate(true);
		op_EAC.setWidth("90px");
		op_EAC.setHeight("20px");
		op_EAC.setValue("0");
		mainLayout.addComponent(op_EAC, "top:440.0px;left:670.0px;");

		// op_Eng_Budget
		op_Eng_Budget = new TextField();
		op_Eng_Budget.setImmediate(true);
		op_Eng_Budget.setWidth("90px");
		op_Eng_Budget.setHeight("20px");
		mainLayout.addComponent(op_Eng_Budget, "top:460.0px;left:220.0px;");

		// op_Eng_Actual
		op_Eng_Actual = new TextField();
		op_Eng_Actual.setImmediate(true);
		op_Eng_Actual.setWidth("90px");
		op_Eng_Actual.setHeight("20px");
		op_Eng_Actual.setValue("0");
		mainLayout.addComponent(op_Eng_Actual, "top:460.0px;left:310.0px;");

		// op_Eng_Commit
		op_Eng_Commit = new TextField();
		op_Eng_Commit.setImmediate(true);
		op_Eng_Commit.setWidth("90px");
		op_Eng_Commit.setHeight("20px");
		op_Eng_Commit.setValue("0");
		mainLayout.addComponent(op_Eng_Commit, "top:460.0px;left:400.0px;");

		// op_Eng_AdditionalCost
		op_Eng_AdditionalCost = new TextField();
		op_Eng_AdditionalCost.setImmediate(true);
		op_Eng_AdditionalCost.setWidth("90px");
		op_Eng_AdditionalCost.setHeight("20px");
		mainLayout.addComponent(op_Eng_AdditionalCost, "top:460.0px;left:490.0px;");

		// op_Eng_ETC
		op_Eng_ETC = new TextField();
		op_Eng_ETC.setImmediate(true);
		op_Eng_ETC.setWidth("90px");
		op_Eng_ETC.setHeight("20px");
		op_Eng_ETC.setValue("0");
		mainLayout.addComponent(op_Eng_ETC, "top:460.0px;left:580.0px;");

		// op_Eng_EAC
		op_Eng_EAC = new TextField();
		op_Eng_EAC.setImmediate(true);
		op_Eng_EAC.setWidth("90px");
		op_Eng_EAC.setHeight("20px");
		op_Eng_EAC.setValue("0");
		mainLayout.addComponent(op_Eng_EAC, "top:460.0px;left:670.0px;");

		// op_Procure_Budget
		op_Procure_Budget = new TextField();
		op_Procure_Budget.setImmediate(true);
		op_Procure_Budget.setWidth("90px");
		op_Procure_Budget.setHeight("20px");
		mainLayout.addComponent(op_Procure_Budget, "top:480.0px;left:220.0px;");

		// op_Procure_Actual
		op_Procure_Actual = new TextField();
		op_Procure_Actual.setImmediate(true);
		op_Procure_Actual.setWidth("90px");
		op_Procure_Actual.setHeight("20px");
		op_Procure_Actual.setValue("0");
		mainLayout.addComponent(op_Procure_Actual, "top:480.0px;left:310.0px;");

		// op_Procure_Commit
		op_Procure_Commit = new TextField();
		op_Procure_Commit.setImmediate(true);
		op_Procure_Commit.setWidth("90px");
		op_Procure_Commit.setHeight("20px");
		op_Procure_Commit.setValue("0");
		mainLayout.addComponent(op_Procure_Commit, "top:480.0px;left:400.0px;");

		// op_Procure_AdditionalCost
		op_Procure_AdditionalCost = new TextField();
		op_Procure_AdditionalCost.setImmediate(true);
		op_Procure_AdditionalCost.setWidth("90px");
		op_Procure_AdditionalCost.setHeight("20px");
		mainLayout.addComponent(op_Procure_AdditionalCost, "top:480.0px;left:490.0px;");

		// op_Procure_ETC
		op_Procure_ETC = new TextField();
		op_Procure_ETC.setImmediate(true);
		op_Procure_ETC.setWidth("90px");
		op_Procure_ETC.setHeight("20px");
		op_Procure_ETC.setValue("0");
		mainLayout.addComponent(op_Procure_ETC, "top:480.0px;left:580.0px;");

		// op_Procure_EAC
		op_Procure_EAC = new TextField();
		op_Procure_EAC.setImmediate(true);
		op_Procure_EAC.setWidth("90px");
		op_Procure_EAC.setHeight("20px");
		op_Procure_EAC.setValue("0");
		mainLayout.addComponent(op_Procure_EAC, "top:480.0px;left:670.0px;");

		// op_Construction_Budget
		op_Construction_Budget = new TextField();
		op_Construction_Budget.setImmediate(true);
		op_Construction_Budget.setWidth("90px");
		op_Construction_Budget.setHeight("20px");
		mainLayout.addComponent(op_Construction_Budget, "top:500.0px;left:220.0px;");

		// op_Construction_Actual
		op_Construction_Actual = new TextField();
		op_Construction_Actual.setImmediate(true);
		op_Construction_Actual.setWidth("90px");
		op_Construction_Actual.setHeight("20px");
		op_Construction_Actual.setValue("0");
		mainLayout.addComponent(op_Construction_Actual, "top:500.0px;left:310.0px;");

		// op_Construction_Commit
		op_Construction_Commit = new TextField();
		op_Construction_Commit.setImmediate(true);
		op_Construction_Commit.setWidth("90px");
		op_Construction_Commit.setHeight("20px");
		op_Construction_Commit.setValue("0");
		mainLayout.addComponent(op_Construction_Commit, "top:500.0px;left:400.0px;");

		// op_Construction_AdditionalCost
		op_Construction_AdditionalCost = new TextField();
		op_Construction_AdditionalCost.setImmediate(true);
		op_Construction_AdditionalCost.setWidth("90px");
		op_Construction_AdditionalCost.setHeight("20px");
		mainLayout.addComponent(op_Construction_AdditionalCost, "top:500.0px;left:490.0px;");

		// op_Construction_ETC
		op_Construction_ETC = new TextField();
		op_Construction_ETC.setImmediate(true);
		op_Construction_ETC.setWidth("90px");
		op_Construction_ETC.setHeight("20px");
		op_Construction_ETC.setValue("0");
		mainLayout.addComponent(op_Construction_ETC, "top:500.0px;left:580.0px;");

		// op_Construction_EAC
		op_Construction_EAC = new TextField();
		op_Construction_EAC.setImmediate(true);
		op_Construction_EAC.setWidth("90px");
		op_Construction_EAC.setHeight("20px");
		op_Construction_EAC.setValue("0");
		mainLayout.addComponent(op_Construction_EAC, "top:500.0px;left:670.0px;");

		// salvage_Budget
		salvage_Budget = new TextField();
		salvage_Budget.setImmediate(true);
		salvage_Budget.setWidth("90px");
		salvage_Budget.setHeight("20px");
		mainLayout.addComponent(salvage_Budget, "top:520.0px;left:220.0px;");

		// salvage_Actual
		salvage_Actual = new TextField();
		salvage_Actual.setImmediate(true);
		salvage_Actual.setWidth("90px");
		salvage_Actual.setHeight("20px");
		salvage_Actual.setValue("0");
		mainLayout.addComponent(salvage_Actual, "top:520.0px;left:310.0px;");

		// salvage_Commit
		salvage_Commit = new TextField();
		salvage_Commit.setImmediate(true);
		salvage_Commit.setWidth("90px");
		salvage_Commit.setHeight("20px");
		salvage_Commit.setValue("0");
		mainLayout.addComponent(salvage_Commit, "top:520.0px;left:400.0px;");

		// salvage_AdditionalCost
		salvage_AdditionalCost = new TextField();
		salvage_AdditionalCost.setImmediate(true);
		salvage_AdditionalCost.setWidth("90px");
		salvage_AdditionalCost.setHeight("20px");
		mainLayout.addComponent(salvage_AdditionalCost, "top:520.0px;left:490.0px;");

		// salvage_ETC
		salvage_ETC = new TextField();
		salvage_ETC.setImmediate(true);
		salvage_ETC.setWidth("90px");
		salvage_ETC.setHeight("20px");
		salvage_ETC.setValue("0");
		mainLayout.addComponent(salvage_ETC, "top:520.0px;left:580.0px;");

		// salvage_EAC
		salvage_EAC = new TextField();
		salvage_EAC.setImmediate(true);
		salvage_EAC.setWidth("90px");
		salvage_EAC.setHeight("20px");
		salvage_EAC.setValue("0");
		mainLayout.addComponent(salvage_EAC, "top:520.0px;left:670.0px;");

		// withdraw_Budget
		withdraw_Budget = new TextField();
		withdraw_Budget.setImmediate(true);
		withdraw_Budget.setWidth("90px");
		withdraw_Budget.setHeight("20px");
		mainLayout.addComponent(withdraw_Budget, "top:540.0px;left:220.0px;");

		// withdraw_Actual
		withdraw_Actual = new TextField();
		withdraw_Actual.setImmediate(true);
		withdraw_Actual.setWidth("90px");
		withdraw_Actual.setHeight("20px");
		withdraw_Actual.setValue("0");
		mainLayout.addComponent(withdraw_Actual, "top:540.0px;left:310.0px;");

		// withdraw_Commit
		withdraw_Commit = new TextField();
		withdraw_Commit.setImmediate(true);
		withdraw_Commit.setWidth("90px");
		withdraw_Commit.setHeight("20px");
		withdraw_Commit.setValue("0");
		mainLayout.addComponent(withdraw_Commit, "top:540.0px;left:400.0px;");

		// withdraw_AdditionalCost
		withdraw_AdditionalCost = new TextField();
		withdraw_AdditionalCost.setImmediate(true);
		withdraw_AdditionalCost.setWidth("90px");
		withdraw_AdditionalCost.setHeight("20px");
		mainLayout.addComponent(withdraw_AdditionalCost, "top:540.0px;left:490.0px;");

		// withdraw_ETC
		withdraw_ETC = new TextField();
		withdraw_ETC.setImmediate(true);
		withdraw_ETC.setWidth("90px");
		withdraw_ETC.setHeight("20px");
		withdraw_ETC.setValue("0");
		mainLayout.addComponent(withdraw_ETC, "top:540.0px;left:580.0px;");

		// withdraw_EAC
		withdraw_EAC = new TextField();
		withdraw_EAC.setImmediate(true);
		withdraw_EAC.setWidth("90px");
		withdraw_EAC.setHeight("20px");
		withdraw_EAC.setValue("0");
		mainLayout.addComponent(withdraw_EAC, "top:540.0px;left:670.0px;");

		// subtotal_Budget
		subtotal_Budget = new TextField();
		subtotal_Budget.setImmediate(true);
		subtotal_Budget.setWidth("90px");
		subtotal_Budget.setHeight("20px");
		subtotal_Budget.setValue("0");
		mainLayout.addComponent(subtotal_Budget, "top:560.0px;left:220.0px;");

		// subtotal_Actual
		subtotal_Actual = new TextField();
		subtotal_Actual.setImmediate(true);
		subtotal_Actual.setWidth("90px");
		subtotal_Actual.setHeight("20px");
		subtotal_Actual.setValue("0");
		mainLayout.addComponent(subtotal_Actual, "top:560.0px;left:310.0px;");

		// subtotal_Commit
		subtotal_Commit = new TextField();
		subtotal_Commit.setImmediate(true);
		subtotal_Commit.setWidth("90px");
		subtotal_Commit.setHeight("20px");
		subtotal_Commit.setValue("0");
		mainLayout.addComponent(subtotal_Commit, "top:560.0px;left:400.0px;");

		// subtotal_AdditionalCost
		subtotal_AdditionalCost = new TextField();
		subtotal_AdditionalCost.setImmediate(true);
		subtotal_AdditionalCost.setWidth("90px");
		subtotal_AdditionalCost.setHeight("20px");
		subtotal_AdditionalCost.setValue("0");
		mainLayout.addComponent(subtotal_AdditionalCost, "top:560.0px;left:490.0px;");

		// subtotal_ETC
		subtotal_ETC = new TextField();
		subtotal_ETC.setImmediate(true);
		subtotal_ETC.setWidth("90px");
		subtotal_ETC.setHeight("20px");
		subtotal_ETC.setValue("0");
		mainLayout.addComponent(subtotal_ETC, "top:560.0px;left:580.0px;");

		// subtotal_EAC
		subtotal_EAC = new TextField();
		subtotal_EAC.setImmediate(true);
		subtotal_EAC.setWidth("90px");
		subtotal_EAC.setHeight("20px");
		subtotal_EAC.setValue("0");
		mainLayout.addComponent(subtotal_EAC, "top:560.0px;left:670.0px;");

		// risk_Budget
		risk_Budget = new TextField();
		risk_Budget.setImmediate(true);
		risk_Budget.setWidth("90px");
		risk_Budget.setHeight("20px");
		mainLayout.addComponent(risk_Budget, "top:580.0px;left:220.0px;");

		// risk_Actual
		risk_Actual = new TextField();
		risk_Actual.setImmediate(true);
		risk_Actual.setWidth("90px");
		risk_Actual.setHeight("20px");
		risk_Actual.setValue("0");
		mainLayout.addComponent(risk_Actual, "top:580.0px;left:310.0px;");

		// risk_Commit
		risk_Commit = new TextField();
		risk_Commit.setImmediate(true);
		risk_Commit.setWidth("90px");
		risk_Commit.setHeight("20px");
		risk_Commit.setValue("0");
		mainLayout.addComponent(risk_Commit, "top:580.0px;left:400.0px;");

		// risk_AdditionalCost
		risk_AdditionalCost = new TextField();
		risk_AdditionalCost.setImmediate(true);
		risk_AdditionalCost.setWidth("90px");
		risk_AdditionalCost.setHeight("20px");
		mainLayout.addComponent(risk_AdditionalCost, "top:580.0px;left:490.0px;");

		// risk_ETC
		risk_ETC = new TextField();
		risk_ETC.setImmediate(true);
		risk_ETC.setWidth("90px");
		risk_ETC.setHeight("20px");
		risk_ETC.setValue("0");
		mainLayout.addComponent(risk_ETC, "top:580.0px;left:580.0px;");

		// risk_EAC
		risk_EAC = new TextField();
		risk_EAC.setImmediate(true);
		risk_EAC.setWidth("90px");
		risk_EAC.setHeight("20px");
		risk_EAC.setValue("0");
		mainLayout.addComponent(risk_EAC, "top:580.0px;left:670.0px;");

		// total_Budget
		total_Budget = new TextField();
		total_Budget.setImmediate(true);
		total_Budget.setWidth("90px");
		total_Budget.setHeight("20px");
		total_Budget.setValue("0");
		mainLayout.addComponent(total_Budget, "top:600.0px;left:220.0px;");

		// total_Actual
		total_Actual = new TextField();
		total_Actual.setImmediate(true);
		total_Actual.setWidth("90px");
		total_Actual.setHeight("20px");
		total_Actual.setValue("0");
		mainLayout.addComponent(total_Actual, "top:600.0px;left:310.0px;");

		// total_Commit
		total_Commit = new TextField();
		total_Commit.setImmediate(true);
		total_Commit.setWidth("90px");
		total_Commit.setHeight("20px");
		total_Commit.setValue("0");
		mainLayout.addComponent(total_Commit, "top:600.0px;left:400.0px;");

		// total_AdditionalCost
		total_AdditionalCost = new TextField();
		total_AdditionalCost.setImmediate(true);
		total_AdditionalCost.setWidth("90px");
		total_AdditionalCost.setHeight("20px");
		total_AdditionalCost.setValue("0");
		mainLayout.addComponent(total_AdditionalCost, "top:600.0px;left:490.0px;");

		// total_ETC
		total_ETC = new TextField();
		total_ETC.setImmediate(true);
		total_ETC.setWidth("90px");
		total_ETC.setHeight("20px");
		total_ETC.setValue("0");
		mainLayout.addComponent(total_ETC, "top:600.0px;left:580.0px;");

		// total_EAC
		total_EAC = new TextField();
		total_EAC.setImmediate(true);
		total_EAC.setWidth("90px");
		total_EAC.setHeight("20px");
		total_EAC.setValue("0");
		mainLayout.addComponent(total_EAC, "top:600.0px;left:670.0px;");

		return mainLayout;
	}

}
